[workspace]
members = [
    "contracts/cw-infuser",
    "contracts/cw721/*",
    "contracts/whitelist/*",
    "packages/cw-infusions",
    "packages/cw-svg",
    "packages/easy-addr",
    "packages/mtree-tooling",
    "scripts",
    "test-suite",
]
exclude = ["scripts", "test-suite"]
resolver = "2"

[workspace.package]
repository = "https://github.com/permissionlessweb/cw-infuser"
edition = "2021"
resolver = "2"
homepage = "https://permissionless.money"
version = "0.7.3"
authors = ["hard-nett <hardnettt@proton.me>"]
license = "MIT"

[workspace.features]
default = []

[workspace.dependencies]

anyhow = "1"
blake3 = "1.8.3"
cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../cosmwasm/packages/std" }
cw-controllers = { path = "../cw-minus/packages/controllers" }
cw-infuser = { path = "./contracts/cw-infuser" }
cw-infusions = { path = "./packages/cw-infusions" }
cw-orch = { path = "../cw-orchestrator/cw-orch" }
cw-ownable = { path = "../cw-plus-plus/packages/ownable" }
cw-storage-plus = { path = "../cw-storage-plus" }
cw-svg = { path = "./packages/cw-svg" }
cw-svg-minter = { path = "./contracts/cw721/cw721-svg-minter" }
cw-utils = { path = "../cw-minus/packages/cw-utils" }
cw2 = { path = "../cw-minus/packages/cw2" }
cw721 = { path = "../cw-nfts/packages/cw721" }
hex = "0.4"
mtree-tooling = { path = "./packages/mtree-tooling" }
schemars = "0.8.16"
semver = "1"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.2", default-features = false }
thiserror = { version = "1.0.58" }
url = "2.2.2"
whitelist-mtree = { path = "./contracts/whitelist/whitelist-merkletree" }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
