# Auto-generated by gen-tools from cw721-svg-minter
# Do not edit manually.

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Any, List, Optional

cwsvgminter = Any

