# Auto-generated by gen-tools from cw-infuser
# Do not edit manually.

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Any, List, Optional

cwinfuser = Any

cwinfusionminter = Any

