/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwInfuser.types";
import * as _1 from "./CwInfuser.client";
import * as _2 from "./CwInfuser.message-composer";
import * as _3 from "./Cw721Svg.types";
import * as _4 from "./Cw721Svg.client";
import * as _5 from "./Cw721Svg.message-composer";
import * as _6 from "./WhitelistMerkletree.types";
import * as _7 from "./WhitelistMerkletree.client";
import * as _8 from "./WhitelistMerkletree.message-composer";
import * as _9 from "./baseClient";
export namespace contracts {
  export const CwInfuser = {
    ..._0,
    ..._1,
    ..._2
  };
  export const Cw721Svg = {
    ..._3,
    ..._4,
    ..._5
  };
  export const WhitelistMerkletree = {
    ..._6,
    ..._7,
    ..._8
  };
  export const baseClient = {
    ..._9
  };
}