/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CwInfuser.types";
import * as _1 from "./CwInfuser.client";
import * as _2 from "./CwInfuser.message-composer";
import * as _3 from "./CwInfusionMinter.types";
import * as _4 from "./CwInfusionMinter.client";
import * as _5 from "./CwInfusionMinter.message-composer";
import * as _6 from "./CwSvgMinter.types";
import * as _7 from "./CwSvgMinter.client";
import * as _8 from "./CwSvgMinter.message-composer";
import * as _9 from "./Cw721Svg.types";
import * as _10 from "./Cw721Svg.client";
import * as _11 from "./Cw721Svg.message-composer";
import * as _12 from "./WhitelistMtree.types";
import * as _13 from "./WhitelistMtree.client";
import * as _14 from "./WhitelistMtree.message-composer";
import * as _15 from "./DaoCalendar.types";
import * as _16 from "./DaoCalendar.client";
import * as _17 from "./DaoCalendar.message-composer";
import * as _18 from "./baseClient";
export namespace contracts {
  export const CwInfuser = {
    ..._0,
    ..._1,
    ..._2
  };
  export const CwInfusionMinter = {
    ..._3,
    ..._4,
    ..._5
  };
  export const CwSvgMinter = {
    ..._6,
    ..._7,
    ..._8
  };
  export const Cw721Svg = {
    ..._9,
    ..._10,
    ..._11
  };
  export const WhitelistMtree = {
    ..._12,
    ..._13,
    ..._14
  };
  export const DaoCalendar = {
    ..._15,
    ..._16,
    ..._17
  };
  export const baseClient = {
    ..._18
  };
}