/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { Uint128, Binary, VariableKind, InstantiateMsg, PriceTier, Coin, TemplateSlot, VariableDef, ExecuteMsg, Expiration, Timestamp, Uint64, Action, QueryMsg, AllNftInfoResponseForSvgMetadata, OwnerOfResponse, Approval, NftInfoResponseForSvgMetadata, SvgMetadata, TokenParam, OperatorsResponse, TokensResponse, ApprovalResponse, ApprovalsResponse, Addr, ConfigResponse, MintConfig, ContractInfoResponse, MintCountResponse, OwnershipForAddr, NumTokensResponse, OwnershipForString, SvgTokenUriResponse, SvgTemplateResponse, NullableAddr } from "./Cw721Svg.types";
export interface Cw721SvgMsg {
  contractAddress: string;
  sender: string;
  mint: ({
    allocation,
    amount,
    proofHashes
  }: {
    allocation?: number;
    amount: number;
    proofHashes?: string[];
  }, funds_?: Coin[]) => EncodeObject;
  pause: ({
    pause
  }: {
    pause: boolean;
  }, funds_?: Coin[]) => EncodeObject;
  updateWhitelist: ({
    address
  }: {
    address?: string;
  }, funds_?: Coin[]) => EncodeObject;
  transferNft: ({
    recipient,
    tokenId
  }: {
    recipient: string;
    tokenId: string;
  }, funds_?: Coin[]) => EncodeObject;
  sendNft: ({
    contract,
    msg,
    tokenId
  }: {
    contract: string;
    msg: Binary;
    tokenId: string;
  }, funds_?: Coin[]) => EncodeObject;
  approve: ({
    expires,
    spender,
    tokenId
  }: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  }, funds_?: Coin[]) => EncodeObject;
  revoke: ({
    spender,
    tokenId
  }: {
    spender: string;
    tokenId: string;
  }, funds_?: Coin[]) => EncodeObject;
  approveAll: ({
    expires,
    operator
  }: {
    expires?: Expiration;
    operator: string;
  }, funds_?: Coin[]) => EncodeObject;
  revokeAll: ({
    operator
  }: {
    operator: string;
  }, funds_?: Coin[]) => EncodeObject;
  updateOwnership: (action: Action, funds_?: Coin[]) => EncodeObject;
}
export class Cw721SvgMsgComposer implements Cw721SvgMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.mint = this.mint.bind(this);
    this.pause = this.pause.bind(this);
    this.updateWhitelist = this.updateWhitelist.bind(this);
    this.transferNft = this.transferNft.bind(this);
    this.sendNft = this.sendNft.bind(this);
    this.approve = this.approve.bind(this);
    this.revoke = this.revoke.bind(this);
    this.approveAll = this.approveAll.bind(this);
    this.revokeAll = this.revokeAll.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  mint = ({
    allocation,
    amount,
    proofHashes
  }: {
    allocation?: number;
    amount: number;
    proofHashes?: string[];
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          mint: {
            allocation,
            amount,
            proof_hashes: proofHashes
          }
        })),
        funds: funds_
      })
    };
  };
  pause = ({
    pause
  }: {
    pause: boolean;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          pause: {
            pause
          }
        })),
        funds: funds_
      })
    };
  };
  updateWhitelist = ({
    address
  }: {
    address?: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_whitelist: {
            address
          }
        })),
        funds: funds_
      })
    };
  };
  transferNft = ({
    recipient,
    tokenId
  }: {
    recipient: string;
    tokenId: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          transfer_nft: {
            recipient,
            token_id: tokenId
          }
        })),
        funds: funds_
      })
    };
  };
  sendNft = ({
    contract,
    msg,
    tokenId
  }: {
    contract: string;
    msg: Binary;
    tokenId: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          send_nft: {
            contract,
            msg,
            token_id: tokenId
          }
        })),
        funds: funds_
      })
    };
  };
  approve = ({
    expires,
    spender,
    tokenId
  }: {
    expires?: Expiration;
    spender: string;
    tokenId: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          approve: {
            expires,
            spender,
            token_id: tokenId
          }
        })),
        funds: funds_
      })
    };
  };
  revoke = ({
    spender,
    tokenId
  }: {
    spender: string;
    tokenId: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          revoke: {
            spender,
            token_id: tokenId
          }
        })),
        funds: funds_
      })
    };
  };
  approveAll = ({
    expires,
    operator
  }: {
    expires?: Expiration;
    operator: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          approve_all: {
            expires,
            operator
          }
        })),
        funds: funds_
      })
    };
  };
  revokeAll = ({
    operator
  }: {
    operator: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          revoke_all: {
            operator
          }
        })),
        funds: funds_
      })
    };
  };
  updateOwnership = (action: Action, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_ownership: action
        })),
        funds: funds_
      })
    };
  };
}