/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Binary = string;
export type VariableKind = {
  options: string[];
} | {
  range: {
    max: string;
    min: string;
    precision: number;
  };
};
export interface InstantiateMsg {
  mint_end_time?: number | null;
  mint_start_time?: number | null;
  name: string;
  owner?: string | null;
  payment_address?: string | null;
  price_tiers: PriceTier[];
  seed: Binary;
  svg_template: string;
  symbol: string;
  template_slots: TemplateSlot[];
  total: number;
  variables: VariableDef[];
  whitelist?: string | null;
}
export interface PriceTier {
  price: Coin;
  until_count: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface TemplateSlot {
  end: number;
  start: number;
  var_idx: number;
}
export interface VariableDef {
  kind: VariableKind;
  name: string;
}
export type ExecuteMsg = {
  mint: {
    allocation?: number | null;
    amount: number;
    proof_hashes?: string[] | null;
  };
} | {
  pause: {
    pause: boolean;
  };
} | {
  update_whitelist: {
    address?: string | null;
  };
} | {
  transfer_nft: {
    recipient: string;
    token_id: string;
  };
} | {
  send_nft: {
    contract: string;
    msg: Binary;
    token_id: string;
  };
} | {
  approve: {
    expires?: Expiration | null;
    spender: string;
    token_id: string;
  };
} | {
  revoke: {
    spender: string;
    token_id: string;
  };
} | {
  approve_all: {
    expires?: Expiration | null;
    operator: string;
  };
} | {
  revoke_all: {
    operator: string;
  };
} | {
  update_ownership: Action;
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type QueryMsg = {
  owner_of: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  approval: {
    include_expired?: boolean | null;
    spender: string;
    token_id: string;
  };
} | {
  approvals: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  all_operators: {
    include_expired?: boolean | null;
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  num_tokens: {};
} | {
  contract_info: {};
} | {
  nft_info: {
    token_id: string;
  };
} | {
  all_nft_info: {
    include_expired?: boolean | null;
    token_id: string;
  };
} | {
  tokens: {
    limit?: number | null;
    owner: string;
    start_after?: string | null;
  };
} | {
  all_tokens: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  minter: {};
} | {
  svg_token_uri: {
    token_id: string;
  };
} | {
  svg_placeholder: {
    seed?: string | null;
  };
} | {
  config: {};
} | {
  svg_template: {};
} | {
  whitelist: {};
} | {
  mint_count: {
    address: string;
  };
} | {
  wl_mint_count: {
    address: string;
  };
} | {
  ownership: {};
};
export interface AllNftInfoResponseForSvgMetadata {
  access: OwnerOfResponse;
  info: NftInfoResponseForSvgMetadata;
}
export interface OwnerOfResponse {
  approvals: Approval[];
  owner: string;
}
export interface Approval {
  expires: Expiration;
  spender: string;
}
export interface NftInfoResponseForSvgMetadata {
  extension: SvgMetadata;
  token_uri?: string | null;
}
export interface SvgMetadata {
  params: TokenParam[];
}
export interface TokenParam {
  name: string;
  value: string;
}
export interface OperatorsResponse {
  operators: Approval[];
}
export interface TokensResponse {
  tokens: string[];
}
export interface ApprovalResponse {
  approval: Approval;
}
export interface ApprovalsResponse {
  approvals: Approval[];
}
export type Addr = string;
export interface ConfigResponse {
  config: MintConfig;
}
export interface MintConfig {
  mint_count: number;
  mint_end_time?: Timestamp | null;
  mint_start_time: Timestamp;
  paused: boolean;
  payment_address: Addr;
  price_tiers: PriceTier[];
  seed: Binary;
  total: number;
}
export interface ContractInfoResponse {
  name: string;
  symbol: string;
}
export interface MintCountResponse {
  address: string;
  count: number;
}
export interface OwnershipForAddr {
  owner?: Addr | null;
  pending_expiry?: Expiration | null;
  pending_owner?: Addr | null;
}
export interface NumTokensResponse {
  count: number;
}
export interface OwnershipForString {
  owner?: string | null;
  pending_expiry?: Expiration | null;
  pending_owner?: string | null;
}
export interface SvgTokenUriResponse {
  svg: string;
}
export interface SvgTemplateResponse {
  template: string;
}
export type NullableAddr = Addr | null;