// Auto-generated by gen-tools.
import type { Cw721Svg as Cw721SvgType } from './Cw721Svg.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface Cw721SvgQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

  ownerOf(params: Extract<Cw721SvgType, { owner_of: unknown }>['owner_of']): Promise<unknown>;
  approval(params: Extract<Cw721SvgType, { approval: unknown }>['approval']): Promise<unknown>;
  approvals(params: Extract<Cw721SvgType, { approvals: unknown }>['approvals']): Promise<unknown>;
  allOperators(params: Extract<Cw721SvgType, { all_operators: unknown }>['all_operators']): Promise<unknown>;
  numTokens(params: Extract<Cw721SvgType, { num_tokens: unknown }>['num_tokens']): Promise<unknown>;
  contractInfo(params: Extract<Cw721SvgType, { contract_info: unknown }>['contract_info']): Promise<unknown>;
  nftInfo(params: Extract<Cw721SvgType, { nft_info: unknown }>['nft_info']): Promise<unknown>;
  allNftInfo(params: Extract<Cw721SvgType, { all_nft_info: unknown }>['all_nft_info']): Promise<unknown>;
  tokens(params: Extract<Cw721SvgType, { tokens: unknown }>['tokens']): Promise<unknown>;
  allTokens(params: Extract<Cw721SvgType, { all_tokens: unknown }>['all_tokens']): Promise<unknown>;
  minter(params: Extract<Cw721SvgType, { minter: unknown }>['minter']): Promise<unknown>;
  svgTokenUri(params: Extract<Cw721SvgType, { svg_token_uri: unknown }>['svg_token_uri']): Promise<unknown>;
  svgPlaceholder(params: Extract<Cw721SvgType, { svg_placeholder: unknown }>['svg_placeholder']): Promise<unknown>;
  config(params: Extract<Cw721SvgType, { config: unknown }>['config']): Promise<unknown>;
  svgTemplate(params: Extract<Cw721SvgType, { svg_template: unknown }>['svg_template']): Promise<unknown>;
  whitelist(params: Extract<Cw721SvgType, { whitelist: unknown }>['whitelist']): Promise<unknown>;
  mintCount(params: Extract<Cw721SvgType, { mint_count: unknown }>['mint_count']): Promise<unknown>;
  wlMintCount(params: Extract<Cw721SvgType, { wl_mint_count: unknown }>['wl_mint_count']): Promise<unknown>;
  ownership(params: Extract<Cw721SvgType, { ownership: unknown }>['ownership']): Promise<unknown>;
}

export interface Cw721SvgExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

  mint(params: Extract<Cw721SvgType, { mint: unknown }>['mint']): Promise<string>;
  pause(params: Extract<Cw721SvgType, { pause: unknown }>['pause']): Promise<string>;
  updateWhitelist(params: Extract<Cw721SvgType, { update_whitelist: unknown }>['update_whitelist']): Promise<string>;
  transferNft(params: Extract<Cw721SvgType, { transfer_nft: unknown }>['transfer_nft']): Promise<string>;
  sendNft(params: Extract<Cw721SvgType, { send_nft: unknown }>['send_nft']): Promise<string>;
  approve(params: Extract<Cw721SvgType, { approve: unknown }>['approve']): Promise<string>;
  revoke(params: Extract<Cw721SvgType, { revoke: unknown }>['revoke']): Promise<string>;
  approveAll(params: Extract<Cw721SvgType, { approve_all: unknown }>['approve_all']): Promise<string>;
  revokeAll(params: Extract<Cw721SvgType, { revoke_all: unknown }>['revoke_all']): Promise<string>;
  updateOwnership(params: Extract<Cw721SvgType, { update_ownership: unknown }>['update_ownership']): Promise<string>;
}
