/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { Uint128, Binary, VariableKind, InstantiateMsg, PriceTier, Coin, VariableDef, ExecuteMsg, Expiration, Timestamp, Uint64, Action, QueryMsg, AllNftInfoResponseForSvgMetadata, OwnerOfResponse, Approval, NftInfoResponseForSvgMetadata, SvgMetadata, TokenParam, OperatorsResponse, TokensResponse, ApprovalResponse, ApprovalsResponse, Addr, ConfigResponse, MintConfig, ContractInfoResponse, MintCountResponse, OwnershipForAddr, NumTokensResponse, OwnershipForString, SvgTemplateResponse, SvgTokenUriResponse, NullableAddr } from "./Cw721Svg.types";
import { Cw721SvgQueryClient } from "./Cw721Svg.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<Cw721SvgQueryClient, QueryClientParams>({
  key: "cw721SvgQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new Cw721SvgQueryClient(client, contractAddress);
  }
});
export const ownerOfSelector = selectorFamily<OwnerOfResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["ownerOf"]>;
}>({
  key: "cw721SvgOwnerOf",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.ownerOf(...params);
  }
});
export const approvalSelector = selectorFamily<ApprovalResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["approval"]>;
}>({
  key: "cw721SvgApproval",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.approval(...params);
  }
});
export const approvalsSelector = selectorFamily<ApprovalsResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["approvals"]>;
}>({
  key: "cw721SvgApprovals",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.approvals(...params);
  }
});
export const allOperatorsSelector = selectorFamily<OperatorsResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["allOperators"]>;
}>({
  key: "cw721SvgAllOperators",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.allOperators(...params);
  }
});
export const numTokensSelector = selectorFamily<NumTokensResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["numTokens"]>;
}>({
  key: "cw721SvgNumTokens",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.numTokens(...params);
  }
});
export const contractInfoSelector = selectorFamily<ContractInfoResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["contractInfo"]>;
}>({
  key: "cw721SvgContractInfo",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.contractInfo(...params);
  }
});
export const nftInfoSelector = selectorFamily<NftInfoResponseForSvgMetadata, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["nftInfo"]>;
}>({
  key: "cw721SvgNftInfo",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.nftInfo(...params);
  }
});
export const allNftInfoSelector = selectorFamily<AllNftInfoResponseForSvgMetadata, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["allNftInfo"]>;
}>({
  key: "cw721SvgAllNftInfo",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.allNftInfo(...params);
  }
});
export const tokensSelector = selectorFamily<TokensResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["tokens"]>;
}>({
  key: "cw721SvgTokens",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.tokens(...params);
  }
});
export const allTokensSelector = selectorFamily<TokensResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["allTokens"]>;
}>({
  key: "cw721SvgAllTokens",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.allTokens(...params);
  }
});
export const minterSelector = selectorFamily<OwnershipForAddr, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["minter"]>;
}>({
  key: "cw721SvgMinter",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.minter(...params);
  }
});
export const svgTokenUriSelector = selectorFamily<SvgTokenUriResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["svgTokenUri"]>;
}>({
  key: "cw721SvgSvgTokenUri",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.svgTokenUri(...params);
  }
});
export const configSelector = selectorFamily<ConfigResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["config"]>;
}>({
  key: "cw721SvgConfig",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.config(...params);
  }
});
export const svgTemplateSelector = selectorFamily<SvgTemplateResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["svgTemplate"]>;
}>({
  key: "cw721SvgSvgTemplate",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.svgTemplate(...params);
  }
});
export const whitelistSelector = selectorFamily<NullableAddr, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["whitelist"]>;
}>({
  key: "cw721SvgWhitelist",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.whitelist(...params);
  }
});
export const mintCountSelector = selectorFamily<MintCountResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["mintCount"]>;
}>({
  key: "cw721SvgMintCount",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.mintCount(...params);
  }
});
export const wlMintCountSelector = selectorFamily<MintCountResponse, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["wlMintCount"]>;
}>({
  key: "cw721SvgWlMintCount",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.wlMintCount(...params);
  }
});
export const ownershipSelector = selectorFamily<OwnershipForString, QueryClientParams & {
  params: Parameters<Cw721SvgQueryClient["ownership"]>;
}>({
  key: "cw721SvgOwnership",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.ownership(...params);
  }
});