/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Uint128, Binary, VariableKind, InstantiateMsg, PriceTier, Coin, VariableDef, ExecuteMsg, Expiration, Timestamp, Uint64, Action, QueryMsg, AllNftInfoResponseForSvgMetadata, OwnerOfResponse, Approval, NftInfoResponseForSvgMetadata, SvgMetadata, TokenParam, OperatorsResponse, TokensResponse, ApprovalResponse, ApprovalsResponse, Addr, ConfigResponse, MintConfig, ContractInfoResponse, MintCountResponse, OwnershipForAddr, NumTokensResponse, OwnershipForString, SvgTemplateResponse, SvgTokenUriResponse, NullableAddr } from "./Cw721Svg.types";
import { Cw721SvgQueryClient } from "./Cw721Svg.client";
export const cw721SvgQueryKeys = {
  contract: ([{
    contract: "cw721Svg"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...cw721SvgQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  ownerOf: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "owner_of",
    args
  }] as const),
  approval: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "approval",
    args
  }] as const),
  approvals: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "approvals",
    args
  }] as const),
  allOperators: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "all_operators",
    args
  }] as const),
  numTokens: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "num_tokens",
    args
  }] as const),
  contractInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "contract_info",
    args
  }] as const),
  nftInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "nft_info",
    args
  }] as const),
  allNftInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "all_nft_info",
    args
  }] as const),
  tokens: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "tokens",
    args
  }] as const),
  allTokens: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "all_tokens",
    args
  }] as const),
  minter: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "minter",
    args
  }] as const),
  svgTokenUri: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "svg_token_uri",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  svgTemplate: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "svg_template",
    args
  }] as const),
  whitelist: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "whitelist",
    args
  }] as const),
  mintCount: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "mint_count",
    args
  }] as const),
  wlMintCount: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "wl_mint_count",
    args
  }] as const),
  ownership: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cw721SvgQueryKeys.address(contractAddress)[0],
    method: "ownership",
    args
  }] as const)
};
export const cw721SvgQueries = {
  ownerOf: <TData = OwnerOfResponse,>({
    client,
    args,
    options
  }: Cw721SvgOwnerOfQuery<TData>): UseQueryOptions<OwnerOfResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.ownerOf(client?.contractAddress, args),
    queryFn: () => client ? client.ownerOf({
      includeExpired: args.includeExpired,
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  approval: <TData = ApprovalResponse,>({
    client,
    args,
    options
  }: Cw721SvgApprovalQuery<TData>): UseQueryOptions<ApprovalResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.approval(client?.contractAddress, args),
    queryFn: () => client ? client.approval({
      includeExpired: args.includeExpired,
      spender: args.spender,
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  approvals: <TData = ApprovalsResponse,>({
    client,
    args,
    options
  }: Cw721SvgApprovalsQuery<TData>): UseQueryOptions<ApprovalsResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.approvals(client?.contractAddress, args),
    queryFn: () => client ? client.approvals({
      includeExpired: args.includeExpired,
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allOperators: <TData = OperatorsResponse,>({
    client,
    args,
    options
  }: Cw721SvgAllOperatorsQuery<TData>): UseQueryOptions<OperatorsResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.allOperators(client?.contractAddress, args),
    queryFn: () => client ? client.allOperators({
      includeExpired: args.includeExpired,
      limit: args.limit,
      owner: args.owner,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  numTokens: <TData = NumTokensResponse,>({
    client,
    options
  }: Cw721SvgNumTokensQuery<TData>): UseQueryOptions<NumTokensResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.numTokens(client?.contractAddress),
    queryFn: () => client ? client.numTokens() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  contractInfo: <TData = ContractInfoResponse,>({
    client,
    options
  }: Cw721SvgContractInfoQuery<TData>): UseQueryOptions<ContractInfoResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.contractInfo(client?.contractAddress),
    queryFn: () => client ? client.contractInfo() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  nftInfo: <TData = NftInfoResponseForSvgMetadata,>({
    client,
    args,
    options
  }: Cw721SvgNftInfoQuery<TData>): UseQueryOptions<NftInfoResponseForSvgMetadata, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.nftInfo(client?.contractAddress, args),
    queryFn: () => client ? client.nftInfo({
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allNftInfo: <TData = AllNftInfoResponseForSvgMetadata,>({
    client,
    args,
    options
  }: Cw721SvgAllNftInfoQuery<TData>): UseQueryOptions<AllNftInfoResponseForSvgMetadata, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.allNftInfo(client?.contractAddress, args),
    queryFn: () => client ? client.allNftInfo({
      includeExpired: args.includeExpired,
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  tokens: <TData = TokensResponse,>({
    client,
    args,
    options
  }: Cw721SvgTokensQuery<TData>): UseQueryOptions<TokensResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.tokens(client?.contractAddress, args),
    queryFn: () => client ? client.tokens({
      limit: args.limit,
      owner: args.owner,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allTokens: <TData = TokensResponse,>({
    client,
    args,
    options
  }: Cw721SvgAllTokensQuery<TData>): UseQueryOptions<TokensResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.allTokens(client?.contractAddress, args),
    queryFn: () => client ? client.allTokens({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  minter: <TData = OwnershipForAddr,>({
    client,
    options
  }: Cw721SvgMinterQuery<TData>): UseQueryOptions<OwnershipForAddr, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.minter(client?.contractAddress),
    queryFn: () => client ? client.minter() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  svgTokenUri: <TData = SvgTokenUriResponse,>({
    client,
    args,
    options
  }: Cw721SvgSvgTokenUriQuery<TData>): UseQueryOptions<SvgTokenUriResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.svgTokenUri(client?.contractAddress, args),
    queryFn: () => client ? client.svgTokenUri({
      tokenId: args.tokenId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: Cw721SvgConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  svgTemplate: <TData = SvgTemplateResponse,>({
    client,
    options
  }: Cw721SvgSvgTemplateQuery<TData>): UseQueryOptions<SvgTemplateResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.svgTemplate(client?.contractAddress),
    queryFn: () => client ? client.svgTemplate() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  whitelist: <TData = NullableAddr,>({
    client,
    options
  }: Cw721SvgWhitelistQuery<TData>): UseQueryOptions<NullableAddr, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.whitelist(client?.contractAddress),
    queryFn: () => client ? client.whitelist() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  mintCount: <TData = MintCountResponse,>({
    client,
    args,
    options
  }: Cw721SvgMintCountQuery<TData>): UseQueryOptions<MintCountResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.mintCount(client?.contractAddress, args),
    queryFn: () => client ? client.mintCount({
      address: args.address
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  wlMintCount: <TData = MintCountResponse,>({
    client,
    args,
    options
  }: Cw721SvgWlMintCountQuery<TData>): UseQueryOptions<MintCountResponse, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.wlMintCount(client?.contractAddress, args),
    queryFn: () => client ? client.wlMintCount({
      address: args.address
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  ownership: <TData = OwnershipForString,>({
    client,
    options
  }: Cw721SvgOwnershipQuery<TData>): UseQueryOptions<OwnershipForString, Error, TData> => ({
    queryKey: cw721SvgQueryKeys.ownership(client?.contractAddress),
    queryFn: () => client ? client.ownership() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface Cw721SvgReactQuery<TResponse, TData = TResponse> {
  client: Cw721SvgQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface Cw721SvgOwnershipQuery<TData> extends Cw721SvgReactQuery<OwnershipForString, TData> {}
export function useCw721SvgOwnershipQuery<TData = OwnershipForString>({
  client,
  options
}: Cw721SvgOwnershipQuery<TData>) {
  return useQuery<OwnershipForString, Error, TData>(cw721SvgQueryKeys.ownership(client?.contractAddress), () => client ? client.ownership() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgWlMintCountQuery<TData> extends Cw721SvgReactQuery<MintCountResponse, TData> {
  args: {
    address: string;
  };
}
export function useCw721SvgWlMintCountQuery<TData = MintCountResponse>({
  client,
  args,
  options
}: Cw721SvgWlMintCountQuery<TData>) {
  return useQuery<MintCountResponse, Error, TData>(cw721SvgQueryKeys.wlMintCount(client?.contractAddress, args), () => client ? client.wlMintCount({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgMintCountQuery<TData> extends Cw721SvgReactQuery<MintCountResponse, TData> {
  args: {
    address: string;
  };
}
export function useCw721SvgMintCountQuery<TData = MintCountResponse>({
  client,
  args,
  options
}: Cw721SvgMintCountQuery<TData>) {
  return useQuery<MintCountResponse, Error, TData>(cw721SvgQueryKeys.mintCount(client?.contractAddress, args), () => client ? client.mintCount({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgWhitelistQuery<TData> extends Cw721SvgReactQuery<NullableAddr, TData> {}
export function useCw721SvgWhitelistQuery<TData = NullableAddr>({
  client,
  options
}: Cw721SvgWhitelistQuery<TData>) {
  return useQuery<NullableAddr, Error, TData>(cw721SvgQueryKeys.whitelist(client?.contractAddress), () => client ? client.whitelist() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgSvgTemplateQuery<TData> extends Cw721SvgReactQuery<SvgTemplateResponse, TData> {}
export function useCw721SvgSvgTemplateQuery<TData = SvgTemplateResponse>({
  client,
  options
}: Cw721SvgSvgTemplateQuery<TData>) {
  return useQuery<SvgTemplateResponse, Error, TData>(cw721SvgQueryKeys.svgTemplate(client?.contractAddress), () => client ? client.svgTemplate() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgConfigQuery<TData> extends Cw721SvgReactQuery<ConfigResponse, TData> {}
export function useCw721SvgConfigQuery<TData = ConfigResponse>({
  client,
  options
}: Cw721SvgConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(cw721SvgQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgSvgTokenUriQuery<TData> extends Cw721SvgReactQuery<SvgTokenUriResponse, TData> {
  args: {
    tokenId: string;
  };
}
export function useCw721SvgSvgTokenUriQuery<TData = SvgTokenUriResponse>({
  client,
  args,
  options
}: Cw721SvgSvgTokenUriQuery<TData>) {
  return useQuery<SvgTokenUriResponse, Error, TData>(cw721SvgQueryKeys.svgTokenUri(client?.contractAddress, args), () => client ? client.svgTokenUri({
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgMinterQuery<TData> extends Cw721SvgReactQuery<OwnershipForAddr, TData> {}
export function useCw721SvgMinterQuery<TData = OwnershipForAddr>({
  client,
  options
}: Cw721SvgMinterQuery<TData>) {
  return useQuery<OwnershipForAddr, Error, TData>(cw721SvgQueryKeys.minter(client?.contractAddress), () => client ? client.minter() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgAllTokensQuery<TData> extends Cw721SvgReactQuery<TokensResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useCw721SvgAllTokensQuery<TData = TokensResponse>({
  client,
  args,
  options
}: Cw721SvgAllTokensQuery<TData>) {
  return useQuery<TokensResponse, Error, TData>(cw721SvgQueryKeys.allTokens(client?.contractAddress, args), () => client ? client.allTokens({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgTokensQuery<TData> extends Cw721SvgReactQuery<TokensResponse, TData> {
  args: {
    limit?: number;
    owner: string;
    startAfter?: string;
  };
}
export function useCw721SvgTokensQuery<TData = TokensResponse>({
  client,
  args,
  options
}: Cw721SvgTokensQuery<TData>) {
  return useQuery<TokensResponse, Error, TData>(cw721SvgQueryKeys.tokens(client?.contractAddress, args), () => client ? client.tokens({
    limit: args.limit,
    owner: args.owner,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgAllNftInfoQuery<TData> extends Cw721SvgReactQuery<AllNftInfoResponseForSvgMetadata, TData> {
  args: {
    includeExpired?: boolean;
    tokenId: string;
  };
}
export function useCw721SvgAllNftInfoQuery<TData = AllNftInfoResponseForSvgMetadata>({
  client,
  args,
  options
}: Cw721SvgAllNftInfoQuery<TData>) {
  return useQuery<AllNftInfoResponseForSvgMetadata, Error, TData>(cw721SvgQueryKeys.allNftInfo(client?.contractAddress, args), () => client ? client.allNftInfo({
    includeExpired: args.includeExpired,
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgNftInfoQuery<TData> extends Cw721SvgReactQuery<NftInfoResponseForSvgMetadata, TData> {
  args: {
    tokenId: string;
  };
}
export function useCw721SvgNftInfoQuery<TData = NftInfoResponseForSvgMetadata>({
  client,
  args,
  options
}: Cw721SvgNftInfoQuery<TData>) {
  return useQuery<NftInfoResponseForSvgMetadata, Error, TData>(cw721SvgQueryKeys.nftInfo(client?.contractAddress, args), () => client ? client.nftInfo({
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgContractInfoQuery<TData> extends Cw721SvgReactQuery<ContractInfoResponse, TData> {}
export function useCw721SvgContractInfoQuery<TData = ContractInfoResponse>({
  client,
  options
}: Cw721SvgContractInfoQuery<TData>) {
  return useQuery<ContractInfoResponse, Error, TData>(cw721SvgQueryKeys.contractInfo(client?.contractAddress), () => client ? client.contractInfo() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgNumTokensQuery<TData> extends Cw721SvgReactQuery<NumTokensResponse, TData> {}
export function useCw721SvgNumTokensQuery<TData = NumTokensResponse>({
  client,
  options
}: Cw721SvgNumTokensQuery<TData>) {
  return useQuery<NumTokensResponse, Error, TData>(cw721SvgQueryKeys.numTokens(client?.contractAddress), () => client ? client.numTokens() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgAllOperatorsQuery<TData> extends Cw721SvgReactQuery<OperatorsResponse, TData> {
  args: {
    includeExpired?: boolean;
    limit?: number;
    owner: string;
    startAfter?: string;
  };
}
export function useCw721SvgAllOperatorsQuery<TData = OperatorsResponse>({
  client,
  args,
  options
}: Cw721SvgAllOperatorsQuery<TData>) {
  return useQuery<OperatorsResponse, Error, TData>(cw721SvgQueryKeys.allOperators(client?.contractAddress, args), () => client ? client.allOperators({
    includeExpired: args.includeExpired,
    limit: args.limit,
    owner: args.owner,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgApprovalsQuery<TData> extends Cw721SvgReactQuery<ApprovalsResponse, TData> {
  args: {
    includeExpired?: boolean;
    tokenId: string;
  };
}
export function useCw721SvgApprovalsQuery<TData = ApprovalsResponse>({
  client,
  args,
  options
}: Cw721SvgApprovalsQuery<TData>) {
  return useQuery<ApprovalsResponse, Error, TData>(cw721SvgQueryKeys.approvals(client?.contractAddress, args), () => client ? client.approvals({
    includeExpired: args.includeExpired,
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgApprovalQuery<TData> extends Cw721SvgReactQuery<ApprovalResponse, TData> {
  args: {
    includeExpired?: boolean;
    spender: string;
    tokenId: string;
  };
}
export function useCw721SvgApprovalQuery<TData = ApprovalResponse>({
  client,
  args,
  options
}: Cw721SvgApprovalQuery<TData>) {
  return useQuery<ApprovalResponse, Error, TData>(cw721SvgQueryKeys.approval(client?.contractAddress, args), () => client ? client.approval({
    includeExpired: args.includeExpired,
    spender: args.spender,
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface Cw721SvgOwnerOfQuery<TData> extends Cw721SvgReactQuery<OwnerOfResponse, TData> {
  args: {
    includeExpired?: boolean;
    tokenId: string;
  };
}
export function useCw721SvgOwnerOfQuery<TData = OwnerOfResponse>({
  client,
  args,
  options
}: Cw721SvgOwnerOfQuery<TData>) {
  return useQuery<OwnerOfResponse, Error, TData>(cw721SvgQueryKeys.ownerOf(client?.contractAddress, args), () => client ? client.ownerOf({
    includeExpired: args.includeExpired,
    tokenId: args.tokenId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}