// Auto-generated by gen-tools.
import type { Cw721Svg } from './Cw721Svg.types';
import type { Coin } from '@cosmjs/amino';
import type { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

export class Cw721SvgMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

  mint(msg: Extract<Cw721SvgType, { mint: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  pause(msg: Extract<Cw721SvgType, { pause: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateWhitelist(msg: Extract<Cw721SvgType, { update_whitelist: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  transferNft(msg: Extract<Cw721SvgType, { transfer_nft: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  sendNft(msg: Extract<Cw721SvgType, { send_nft: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  approve(msg: Extract<Cw721SvgType, { approve: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  revoke(msg: Extract<Cw721SvgType, { revoke: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  approveAll(msg: Extract<Cw721SvgType, { approve_all: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  revokeAll(msg: Extract<Cw721SvgType, { revoke_all: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateOwnership(msg: Extract<Cw721SvgType, { update_ownership: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

}
