// Auto-generated by gen-tools.
// Do not edit manually.

/** Actions that can be taken to alter the contract's ownership */
export type Action =
  | { transfer_ownership: { expiry: Expiration | null; new_owner: string } } |
  | 'accept_ownership' |
  | 'renounce_ownership';

/** A human readable address.

In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.

This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.

This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance. */
export type Addr = string;

export interface Approval {
  /** When the Approval expires (maybe Expiration::never) */
  expires: Expiration;
  /** Account that can transfer/send the token */
  spender: Addr;
}

/** Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.

This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>. See also <https://github.com/CosmWasm/cosmwasm/blob/main/docs/MESSAGE_TYPES.md>. */
export type Binary = string;

export interface Coin {
  amount: Uint256;
  denom: string;
}

/** An empty struct that serves as a placeholder in different places, such as contracts that don't set a custom message.

It is designed to be expressible in correct JSON and JSON Schema but contains no meaningful data. Previously we used enums without cases, but those cannot represented as valid JSON Schema (https://github.com/CosmWasm/cosmwasm/issues/451) */
export interface Empty {
}

/** Expiration represents a point in time when some event happens. It can compare with a BlockInfo and will return is_expired() == true once the condition is hit (and for every block in the future) */
export type Expiration =
  | { at_height: number } |
  | { at_time: Timestamp } |
  | { never: Record<string, unknown> };

export interface MintConfig {
  mint_count: number;
  mint_end_time?: Timestamp | null;
  mint_start_time: Timestamp;
  paused: boolean;
  /** Address that receives mint payments. Defaults to owner. */
  payment_address: Addr;
  /** Ordered price tiers. Empty = free mint. */
  price_tiers: PriceTier[];
  seed: Binary;
  total: number;
}

export interface NftInfoResponseForSvgMetadata {
  /** You can add any custom metadata here when you extend cw721-base */
  extension: SvgMetadata;
  /** Universal resource identifier for this NFT Should point to a JSON file that conforms to the ERC721 Metadata JSON Schema */
  token_uri?: unknown;
}

export interface OwnerOfResponse {
  /** If set this address is approved to transfer/send the token as well */
  approvals: Approval[];
  /** Owner of the token */
  owner: string;
}

/** A price tier that applies until the mint count reaches `until_count`. Tiers must be sorted ascending by `until_count`. Example: [{ until_count: 100, price: 1_000_000utoken }, { until_count: 500, price: 5_000_000utoken }] means: first 100 mints cost 1 token, mints 101-500 cost 5 tokens. */
export interface PriceTier {
  /** Price per token in this tier */
  price: Coin;
  /** This tier applies while mint_count < until_count */
  until_count: number;
}

export interface RgbRange {
  b_max: number;
  b_min: number;
  g_max: number;
  g_min: number;
  r_max: number;
  r_min: number;
}

export interface SvgMetadata {
  params: TokenParam[];
}

export interface TemplateSlot {
  end: number;
  start: number;
  var_idx: number;
}

/** A point in time in nanosecond precision.

This type can represent times from 1970-01-01T00:00:00Z to 2554-07-21T23:34:33Z.

## Examples

``` # use cosmwasm_std::Timestamp; let ts = Timestamp::from_nanos(1_000_000_202); assert_eq!(ts.nanos(), 1_000_000_202); assert_eq!(ts.seconds(), 1); assert_eq!(ts.subsec_nanos(), 202);

let ts = ts.plus_seconds(2); assert_eq!(ts.nanos(), 3_000_000_202); assert_eq!(ts.seconds(), 3); assert_eq!(ts.subsec_nanos(), 202); ``` */
export type Timestamp = unknown;

export interface TokenParam {
  name: string;
  value: string;
}

/** An implementation of u256 that is using strings for JSON encoding/decoding, such that the full u256 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `new` to create instances out of u128, `from` for other primitive uint types or `from_be_bytes` to provide big endian bytes:

``` # use cosmwasm_std::Uint256; let a = Uint256::new(258u128); let b = Uint256::from(258u16); let c = Uint256::from_be_bytes([ 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 1u8, 2u8, ]); assert_eq!(a, b); assert_eq!(a, c); ``` */
export type Uint256 = string;

/** A thin wrapper around u64 that is using strings for JSON encoding/decoding, such that the full u64 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `from` to create instances of this and `u64` to get the value out:

``` # use cosmwasm_std::Uint64; let a = Uint64::from(42u64); assert_eq!(a.u64(), 42);

let b = Uint64::from(70u32); assert_eq!(b.u64(), 70); ``` */
export type Uint64 = string;

export interface VariableDef {
  kind: VariableKind;
  name: string;
}

export type VariableKind =
  | { options: string[] } |
  | { range: { max: string; min: string; precision: number } } |
  | 'rgb' |
  | { rgb_styled: RgbRange[] };

export interface InstantiateMsg {
  mint_end_time?: unknown;
  mint_start_time?: unknown;
  name: string;
  owner?: unknown;
  /** Address to receive mint payments. Defaults to owner/sender. */
  payment_address?: unknown;
  /** Price tiers for minting. Empty or None = free mint. */
  price_tiers: PriceTier[];
  seed: Binary;
  svg_template: string;
  symbol: string;
  /** Pre-computed placeholder positions in the SVG template. Each slot maps a `${varname}` occurrence to its byte offsets and variable index. */
  template_slots: TemplateSlot[];
  total: number;
  variables: VariableDef[];
  /** Optional merkle whitelist contract address. Whitelisted minters bypass fees. */
  whitelist?: unknown;
}

export type ExecuteMsg =
  | { mint: { allocation: number; amount: number; proof_hashes: unknown } } |
  | { pause: { pause: boolean } } |
  | { update_whitelist: { address: unknown } } |
  | { transfer_nft: { recipient: string; token_id: string } } |
  | { send_nft: { contract: string; msg: Binary; token_id: string } } |
  | { approve: { expires: Expiration | null; spender: string; token_id: string } } |
  | { revoke: { spender: string; token_id: string } } |
  | { approve_all: { expires: Expiration | null; operator: string } } |
  | { revoke_all: { operator: string } } |
  | { update_ownership: Action };

export type QueryMsg =
  | { owner_of: { include_expired: unknown; token_id: string } } |
  | { approval: { include_expired: unknown; spender: string; token_id: string } } |
  | { approvals: { include_expired: unknown; token_id: string } } |
  | { all_operators: { include_expired: unknown; limit: unknown; owner: string; start_after: unknown } } |
  | { num_tokens: Record<string, unknown> } |
  | { contract_info: Record<string, unknown> } |
  | { nft_info: { token_id: string } } |
  | { all_nft_info: { include_expired: unknown; token_id: string } } |
  | { tokens: { limit: unknown; owner: string; start_after: unknown } } |
  | { all_tokens: { limit: unknown; start_after: unknown } } |
  | { minter: Record<string, unknown> } |
  | { svg_token_uri: { token_id: string } } |
  | { svg_placeholder: { seed: unknown } } |
  | { config: Record<string, unknown> } |
  | { svg_template: Record<string, unknown> } |
  | { whitelist: Record<string, unknown> } |
  | { mint_count: { address: string } } |
  | { wl_mint_count: { address: string } } |
  | { ownership: Record<string, unknown> };

export interface AllNftInfoResponseForSvgMetadata {
  /** Who can transfer the token */
  access: OwnerOfResponse;
  /** Data on the token itself, */
  info: NftInfoResponseForSvgMetadata;
}

export interface OperatorsResponse {
  operators: Approval[];
}

export interface TokensResponse {
  /** Contains all token_ids in lexicographical ordering If there are more than `limit`, use `start_after` in future queries to achieve pagination. */
  tokens: string[];
}

export interface ApprovalResponse {
  approval: Approval;
}

export interface ApprovalsResponse {
  approvals: Approval[];
}

export interface ConfigResponse {
  config: MintConfig;
}

/** This is a wrapper around CollectionInfo that includes the extension. */
export interface CollectionInfoAndExtensionResponseForNullableEmpty {
  extension?: Empty | null;
  name: string;
  symbol: string;
  updated_at: Timestamp;
}

export interface MintCountResponse {
  address: string;
  count: number;
}

/** The contract's ownership info */
export interface OwnershipForAddr {
  /** The contract's current owner. `None` if the ownership has been renounced. */
  owner?: Addr | null;
  /** The deadline for the pending owner to accept the ownership. `None` if there isn't a pending ownership transfer, or if a transfer exists and it doesn't have a deadline. */
  pending_expiry?: Expiration | null;
  /** The account who has been proposed to take over the ownership. `None` if there isn't a pending ownership transfer. */
  pending_owner?: Addr | null;
}

export interface NumTokensResponse {
  count: number;
}

/** The contract's ownership info */
export interface OwnershipForString {
  /** The contract's current owner. `None` if the ownership has been renounced. */
  owner?: unknown;
  /** The deadline for the pending owner to accept the ownership. `None` if there isn't a pending ownership transfer, or if a transfer exists and it doesn't have a deadline. */
  pending_expiry?: Expiration | null;
  /** The account who has been proposed to take over the ownership. `None` if there isn't a pending ownership transfer. */
  pending_owner?: unknown;
}

export interface SvgTokenUriResponse {
  svg: string;
}

export interface SvgTemplateResponse {
  template: string;
}

