// Auto-generated by gen-tools.
import type { Cw721SvgMinter } from './Cw721SvgMinter.types';
import type { Coin } from '@cosmjs/amino';
import type { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

export class Cw721SvgMinterMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

  createSvgCollection(msg: Extract<Cw721SvgMinterType, { create_svg_collection: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateCodeId(msg: Extract<Cw721SvgMinterType, { update_code_id: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateOwnership(msg: Extract<Cw721SvgMinterType, { update_ownership: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

}
