/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { Uint128, Decimal, InstantiateMsg, Coin, ExecuteMsg, Addr, Timestamp, Uint64, BundleType, Infusion, EligibleNFTCollection, InfusedCollection, RoyaltyInfoResponse, InfusionParamState, BundleBlend, BlendNFTs, BurnParams, CompatibleTraits, WavsBundle, Bundle, NFT, UpdatingConfig, QueryMsg, HexBinary, Config, InfusionState, ArrayOfCompatibleTraits, InfusionsResponse, Boolean, ArrayOfWavsRecordResponse, WavsRecordResponse } from "./CwInfuser.types";
import { CwInfuserQueryClient } from "./CwInfuser.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<CwInfuserQueryClient, QueryClientParams>({
  key: "cwInfuserQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new CwInfuserQueryClient(client, contractAddress);
  }
});
export const configSelector = selectorFamily<Config, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["config"]>;
}>({
  key: "cwInfuserConfig",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.config(...params);
  }
});
export const infusionSelector = selectorFamily<Infusion, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["infusion"]>;
}>({
  key: "cwInfuserInfusion",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.infusion(...params);
  }
});
export const infusionByIdSelector = selectorFamily<InfusionState, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["infusionById"]>;
}>({
  key: "cwInfuserInfusionById",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.infusionById(...params);
  }
});
export const infusionsSelector = selectorFamily<InfusionsResponse, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["infusions"]>;
}>({
  key: "cwInfuserInfusions",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.infusions(...params);
  }
});
export const isInBundleSelector = selectorFamily<Boolean, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["isInBundle"]>;
}>({
  key: "cwInfuserIsInBundle",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.isInBundle(...params);
  }
});
export const infusionGeneticsSelector = selectorFamily<ArrayOfCompatibleTraits, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["infusionGenetics"]>;
}>({
  key: "cwInfuserInfusionGenetics",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.infusionGenetics(...params);
  }
});
export const wavsRecordSelector = selectorFamily<ArrayOfWavsRecordResponse, QueryClientParams & {
  params: Parameters<CwInfuserQueryClient["wavsRecord"]>;
}>({
  key: "cwInfuserWavsRecord",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.wavsRecord(...params);
  }
});