// Auto-generated by gen-tools.
import type { CwInfusionMinter as CwInfusionMinterType } from './CwInfusionMinter.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface CwInfusionMinterQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

  config(params: Extract<CwInfusionMinterType, { config: unknown }>['config']): Promise<Config>;
  infusion(params: Extract<CwInfusionMinterType, { infusion: unknown }>['infusion']): Promise<Infusion>;
  infusionById(params: Extract<CwInfusionMinterType, { infusion_by_id: unknown }>['infusion_by_id']): Promise<unknown>;
  infusions(params: Extract<CwInfusionMinterType, { infusions: unknown }>['infusions']): Promise<unknown>;
  infusionGenetics(params: Extract<CwInfusionMinterType, { infusion_genetics: unknown }>['infusion_genetics']): Promise<unknown>;
  wavsRecord(params: Extract<CwInfusionMinterType, { wavs_record: unknown }>['wavs_record']): Promise<unknown>;
}

export interface CwInfusionMinterExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

  createInfusion(params: Extract<CwInfusionMinterType, { create_infusion: unknown }>['create_infusion']): Promise<string>;
  wavsEntryPoint(params: Extract<CwInfusionMinterType, { wavs_entry_point: unknown }>['wavs_entry_point']): Promise<string>;
  infuse(params: Extract<CwInfusionMinterType, { infuse: unknown }>['infuse']): Promise<string>;
  endInfusion(params: Extract<CwInfusionMinterType, { end_infusion: unknown }>['end_infusion']): Promise<string>;
  updateInfusionBaseUri(params: Extract<CwInfusionMinterType, { update_infusion_base_uri: unknown }>['update_infusion_base_uri']): Promise<string>;
  updateConfig(params: Extract<CwInfusionMinterType, { update_config: unknown }>['update_config']): Promise<string>;
  updateInfusionsEligibleCollectionsOrBundleType(params: Extract<CwInfusionMinterType, { update_infusions_eligible_collections_or_bundle_type: unknown }>['update_infusions_eligible_collections_or_bundle_type']): Promise<string>;
  updateInfusionMintFee(params: Extract<CwInfusionMinterType, { update_infusion_mint_fee: unknown }>['update_infusion_mint_fee']): Promise<string>;
  updateInfusionParams(params: Extract<CwInfusionMinterType, { update_infusion_params: unknown }>['update_infusion_params']): Promise<string>;
  shuffle(params: Extract<CwInfusionMinterType, { shuffle: unknown }>['shuffle']): Promise<string>;
}
