/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export type Decimal = string;
export interface InstantiateMsg {
  contract_owner?: string | null;
  cw721_code_id: number;
  max_bundles?: number | null;
  max_infusions?: number | null;
  max_per_bundle?: number | null;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle?: number | null;
  owner_fee: Decimal;
  wavs_public_key?: string | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  create_infusion: {
    infusions: Infusion[];
  };
} | {
  wavs_entry_point: {
    infusions: WavsBundle[];
  };
} | {
  infuse: {
    bundle: Bundle[];
    id: number;
  };
} | {
  end_infusion: {
    id: number;
  };
} | {
  update_infusion_base_uri: {
    base_uri: string;
    id: number;
  };
} | {
  update_config: {
    config: UpdatingConfig;
  };
} | {
  update_infusions_eligible_collections: {
    id: number;
    to_add: EligibleNFTCollection[];
    to_remove: EligibleNFTCollection[];
  };
} | {
  update_infusion_mint_fee: {
    id: number;
    mint_fee?: Coin | null;
  };
} | {
  update_infusion_bundle_type: {
    bundle_type: BundleType;
    id: number;
  };
} | {
  shuffle: {
    id: number;
  };
};
export type Addr = string;
export type Timestamp = Uint64;
export type Uint64 = string;
export type BundleType = {
  all_of: {};
} | {
  any_of: {
    addrs: Addr[];
  };
} | {
  any_of_blend: {
    blends: BundleBlend[];
  };
};
export interface Infusion {
  collections: EligibleNFTCollection[];
  description?: string | null;
  infused_collection: InfusedCollection;
  infusion_params: InfusionParamState;
  owner?: Addr | null;
  payment_recipient?: Addr | null;
}
export interface EligibleNFTCollection {
  addr: Addr;
  max_req?: number | null;
  min_req: number;
  payment_substitute?: Coin | null;
}
export interface InfusedCollection {
  addr?: string | null;
  admin?: string | null;
  base_uri: string;
  description: string;
  explicit_content?: boolean | null;
  external_link?: string | null;
  image: string;
  name: string;
  num_tokens: number;
  royalty_info?: RoyaltyInfoResponse | null;
  sg: boolean;
  start_trading_time?: Timestamp | null;
  symbol: string;
}
export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}
export interface InfusionParamState {
  bundle_type: BundleType;
  mint_fee?: Coin | null;
  params?: BurnParams | null;
  wavs_enabled: boolean;
}
export interface BundleBlend {
  blend_nfts: BlendNFTs[];
}
export interface BlendNFTs {
  addr: Addr;
  min_req: number;
  payment_substitute: boolean;
}
export interface BurnParams {
  compatible_traits: CompatibleTraits[];
}
export interface CompatibleTraits {
  a: string;
  b: string;
}
export interface WavsBundle {
  infused_ids: string[];
  infuser: string;
  nft_addr: string;
}
export interface Bundle {
  nfts: NFT[];
}
export interface NFT {
  addr: Addr;
  token_id: number;
}
export interface UpdatingConfig {
  code_id?: number | null;
  contract_owner?: string | null;
  max_bundles?: number | null;
  max_infusions?: number | null;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle?: number | null;
  owner_fee?: Decimal | null;
}
export type QueryMsg = {
  config: {};
} | {
  infusion: {
    addr: Addr;
    id: number;
  };
} | {
  infusion_by_id: {
    id: number;
  };
} | {
  infusions: {
    addr: Addr;
    index: number;
  };
} | {
  is_in_bundle: {
    collection_addr: Addr;
    infusion_id: number;
  };
} | {
  infusion_genetics: {
    id: number;
  };
} | {
  wavs_record: {
    burner?: Addr | null;
    nfts: string[];
  };
};
export type HexBinary = string;
export interface Config {
  code_hash: HexBinary;
  code_id: number;
  contract_owner: Addr;
  latest_infusion_id: number;
  max_bundles: number;
  max_infusions: number;
  max_per_bundle: number;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle: number;
  owner_fee: Decimal;
}
export interface InfusionState {
  collections: EligibleNFTCollection[];
  enabled: boolean;
  infused_collection: InfusedCollection;
  infusion_params: InfusionParamState;
  owner: Addr;
  payment_recipient: Addr;
}
export type ArrayOfCompatibleTraits = CompatibleTraits[];
export interface InfusionsResponse {
  infusions: InfusionState[];
}
export type Boolean = boolean;
export type ArrayOfWavsRecordResponse = WavsRecordResponse[];
export interface WavsRecordResponse {
  addr: string;
  count?: number | null;
}