/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { Uint128, Decimal, InstantiateMsg, Coin, ExecuteMsg, Addr, Timestamp, Uint64, BundleType, Infusion, EligibleNFTCollection, InfusedCollection, RoyaltyInfoResponse, InfusionParamState, BundleBlend, BlendNFTs, BurnParams, CompatibleTraits, WavsBundle, Bundle, NFT, UpdatingConfig, UpdateInfusion, QueryMsg, HexBinary, Config, InfusionState, ArrayOfCompatibleTraits, InfusionsResponse, ArrayOfWavsRecordResponse, WavsRecordResponse } from "./CwInfusionMinter.types";
export interface CwInfusionMinterReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  infusion: ({
    addr,
    id
  }: {
    addr: Addr;
    id: number;
  }) => Promise<Infusion>;
  infusionById: ({
    id
  }: {
    id: number;
  }) => Promise<InfusionState>;
  infusions: ({
    addr,
    index
  }: {
    addr: Addr;
    index: number;
  }) => Promise<InfusionsResponse>;
  infusionGenetics: ({
    id
  }: {
    id: number;
  }) => Promise<ArrayOfCompatibleTraits>;
  wavsRecord: ({
    burner,
    nfts
  }: {
    burner?: Addr;
    nfts: string[];
  }) => Promise<ArrayOfWavsRecordResponse>;
}
export class CwInfusionMinterQueryClient implements CwInfusionMinterReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.infusion = this.infusion.bind(this);
    this.infusionById = this.infusionById.bind(this);
    this.infusions = this.infusions.bind(this);
    this.infusionGenetics = this.infusionGenetics.bind(this);
    this.wavsRecord = this.wavsRecord.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  infusion = async ({
    addr,
    id
  }: {
    addr: Addr;
    id: number;
  }): Promise<Infusion> => {
    return this.client.queryContractSmart(this.contractAddress, {
      infusion: {
        addr,
        id
      }
    });
  };
  infusionById = async ({
    id
  }: {
    id: number;
  }): Promise<InfusionState> => {
    return this.client.queryContractSmart(this.contractAddress, {
      infusion_by_id: {
        id
      }
    });
  };
  infusions = async ({
    addr,
    index
  }: {
    addr: Addr;
    index: number;
  }): Promise<InfusionsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      infusions: {
        addr,
        index
      }
    });
  };
  infusionGenetics = async ({
    id
  }: {
    id: number;
  }): Promise<ArrayOfCompatibleTraits> => {
    return this.client.queryContractSmart(this.contractAddress, {
      infusion_genetics: {
        id
      }
    });
  };
  wavsRecord = async ({
    burner,
    nfts
  }: {
    burner?: Addr;
    nfts: string[];
  }): Promise<ArrayOfWavsRecordResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      wavs_record: {
        burner,
        nfts
      }
    });
  };
}
export interface CwInfusionMinterInterface extends CwInfusionMinterReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createInfusion: ({
    infusions
  }: {
    infusions: Infusion[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  wavsEntryPoint: ({
    infusions
  }: {
    infusions: WavsBundle[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  infuse: ({
    bundle,
    id
  }: {
    bundle: Bundle[];
    id: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  endInfusion: ({
    id
  }: {
    id: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateInfusionBaseUri: ({
    baseUri,
    id
  }: {
    baseUri: string;
    id: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    config
  }: {
    config: UpdatingConfig;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateInfusionsEligibleCollectionsOrBundleType: ({
    bundleType,
    id,
    toAdd,
    toRemove
  }: {
    bundleType: BundleType;
    id: number;
    toAdd: EligibleNFTCollection[];
    toRemove: Addr[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateInfusionMintFee: ({
    id,
    mintFee
  }: {
    id: number;
    mintFee?: Coin;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateInfusionParams: ({
    id,
    params
  }: {
    id: number;
    params: UpdateInfusion;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  shuffle: ({
    id
  }: {
    id: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class CwInfusionMinterClient extends CwInfusionMinterQueryClient implements CwInfusionMinterInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createInfusion = this.createInfusion.bind(this);
    this.wavsEntryPoint = this.wavsEntryPoint.bind(this);
    this.infuse = this.infuse.bind(this);
    this.endInfusion = this.endInfusion.bind(this);
    this.updateInfusionBaseUri = this.updateInfusionBaseUri.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updateInfusionsEligibleCollectionsOrBundleType = this.updateInfusionsEligibleCollectionsOrBundleType.bind(this);
    this.updateInfusionMintFee = this.updateInfusionMintFee.bind(this);
    this.updateInfusionParams = this.updateInfusionParams.bind(this);
    this.shuffle = this.shuffle.bind(this);
  }
  createInfusion = async ({
    infusions
  }: {
    infusions: Infusion[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_infusion: {
        infusions
      }
    }, fee_, memo_, funds_);
  };
  wavsEntryPoint = async ({
    infusions
  }: {
    infusions: WavsBundle[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      wavs_entry_point: {
        infusions
      }
    }, fee_, memo_, funds_);
  };
  infuse = async ({
    bundle,
    id
  }: {
    bundle: Bundle[];
    id: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      infuse: {
        bundle,
        id
      }
    }, fee_, memo_, funds_);
  };
  endInfusion = async ({
    id
  }: {
    id: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      end_infusion: {
        id
      }
    }, fee_, memo_, funds_);
  };
  updateInfusionBaseUri = async ({
    baseUri,
    id
  }: {
    baseUri: string;
    id: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_infusion_base_uri: {
        base_uri: baseUri,
        id
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    config
  }: {
    config: UpdatingConfig;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        config
      }
    }, fee_, memo_, funds_);
  };
  updateInfusionsEligibleCollectionsOrBundleType = async ({
    bundleType,
    id,
    toAdd,
    toRemove
  }: {
    bundleType: BundleType;
    id: number;
    toAdd: EligibleNFTCollection[];
    toRemove: Addr[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_infusions_eligible_collections_or_bundle_type: {
        bundle_type: bundleType,
        id,
        to_add: toAdd,
        to_remove: toRemove
      }
    }, fee_, memo_, funds_);
  };
  updateInfusionMintFee = async ({
    id,
    mintFee
  }: {
    id: number;
    mintFee?: Coin;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_infusion_mint_fee: {
        id,
        mint_fee: mintFee
      }
    }, fee_, memo_, funds_);
  };
  updateInfusionParams = async ({
    id,
    params
  }: {
    id: number;
    params: UpdateInfusion;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_infusion_params: {
        id,
        params
      }
    }, fee_, memo_, funds_);
  };
  shuffle = async ({
    id
  }: {
    id: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      shuffle: {
        id
      }
    }, fee_, memo_, funds_);
  };
}