// Auto-generated by gen-tools.
import type { CwInfusionMinter } from './CwInfusionMinter.types';
import type { Coin } from '@cosmjs/amino';
import type { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

export class CwInfusionMinterMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

  createInfusion(msg: Extract<CwInfusionMinterType, { create_infusion: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  wavsEntryPoint(msg: Extract<CwInfusionMinterType, { wavs_entry_point: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  infuse(msg: Extract<CwInfusionMinterType, { infuse: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  endInfusion(msg: Extract<CwInfusionMinterType, { end_infusion: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateInfusionBaseUri(msg: Extract<CwInfusionMinterType, { update_infusion_base_uri: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateConfig(msg: Extract<CwInfusionMinterType, { update_config: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateInfusionsEligibleCollectionsOrBundleType(msg: Extract<CwInfusionMinterType, { update_infusions_eligible_collections_or_bundle_type: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateInfusionMintFee(msg: Extract<CwInfusionMinterType, { update_infusion_mint_fee: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateInfusionParams(msg: Extract<CwInfusionMinterType, { update_infusion_params: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  shuffle(msg: Extract<CwInfusionMinterType, { shuffle: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

}
