/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Uint128, Decimal, InstantiateMsg, Coin, ExecuteMsg, Addr, Timestamp, Uint64, BundleType, Infusion, EligibleNFTCollection, InfusedCollection, RoyaltyInfoResponse, InfusionParamState, BundleBlend, BlendNFTs, BurnParams, CompatibleTraits, WavsBundle, Bundle, NFT, UpdatingConfig, QueryMsg, HexBinary, Config, InfusionState, ArrayOfCompatibleTraits, InfusionsResponse, Boolean, ArrayOfWavsRecordResponse, WavsRecordResponse } from "./CwInfuser.types";
import { CwInfuserQueryClient } from "./CwInfuser.client";
export const cwInfuserQueryKeys = {
  contract: ([{
    contract: "cwInfuser"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...cwInfuserQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  infusion: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "infusion",
    args
  }] as const),
  infusionById: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "infusion_by_id",
    args
  }] as const),
  infusions: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "infusions",
    args
  }] as const),
  isInBundle: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "is_in_bundle",
    args
  }] as const),
  infusionGenetics: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "infusion_genetics",
    args
  }] as const),
  wavsRecord: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...cwInfuserQueryKeys.address(contractAddress)[0],
    method: "wavs_record",
    args
  }] as const)
};
export const cwInfuserQueries = {
  config: <TData = Config,>({
    client,
    options
  }: CwInfuserConfigQuery<TData>): UseQueryOptions<Config, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  infusion: <TData = Infusion,>({
    client,
    args,
    options
  }: CwInfuserInfusionQuery<TData>): UseQueryOptions<Infusion, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusion(client?.contractAddress, args),
    queryFn: () => client ? client.infusion({
      addr: args.addr,
      id: args.id
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  infusionById: <TData = InfusionState,>({
    client,
    args,
    options
  }: CwInfuserInfusionByIdQuery<TData>): UseQueryOptions<InfusionState, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusionById(client?.contractAddress, args),
    queryFn: () => client ? client.infusionById({
      id: args.id
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  infusions: <TData = InfusionsResponse,>({
    client,
    args,
    options
  }: CwInfuserInfusionsQuery<TData>): UseQueryOptions<InfusionsResponse, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusions(client?.contractAddress, args),
    queryFn: () => client ? client.infusions({
      addr: args.addr,
      index: args.index
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  isInBundle: <TData = Boolean,>({
    client,
    args,
    options
  }: CwInfuserIsInBundleQuery<TData>): UseQueryOptions<Boolean, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.isInBundle(client?.contractAddress, args),
    queryFn: () => client ? client.isInBundle({
      collectionAddr: args.collectionAddr,
      infusionId: args.infusionId
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  infusionGenetics: <TData = ArrayOfCompatibleTraits,>({
    client,
    args,
    options
  }: CwInfuserInfusionGeneticsQuery<TData>): UseQueryOptions<ArrayOfCompatibleTraits, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.infusionGenetics(client?.contractAddress, args),
    queryFn: () => client ? client.infusionGenetics({
      id: args.id
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  wavsRecord: <TData = ArrayOfWavsRecordResponse,>({
    client,
    args,
    options
  }: CwInfuserWavsRecordQuery<TData>): UseQueryOptions<ArrayOfWavsRecordResponse, Error, TData> => ({
    queryKey: cwInfuserQueryKeys.wavsRecord(client?.contractAddress, args),
    queryFn: () => client ? client.wavsRecord({
      burner: args.burner,
      nfts: args.nfts
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface CwInfuserReactQuery<TResponse, TData = TResponse> {
  client: CwInfuserQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface CwInfuserWavsRecordQuery<TData> extends CwInfuserReactQuery<ArrayOfWavsRecordResponse, TData> {
  args: {
    burner?: Addr;
    nfts: string[];
  };
}
export function useCwInfuserWavsRecordQuery<TData = ArrayOfWavsRecordResponse>({
  client,
  args,
  options
}: CwInfuserWavsRecordQuery<TData>) {
  return useQuery<ArrayOfWavsRecordResponse, Error, TData>(cwInfuserQueryKeys.wavsRecord(client?.contractAddress, args), () => client ? client.wavsRecord({
    burner: args.burner,
    nfts: args.nfts
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserInfusionGeneticsQuery<TData> extends CwInfuserReactQuery<ArrayOfCompatibleTraits, TData> {
  args: {
    id: number;
  };
}
export function useCwInfuserInfusionGeneticsQuery<TData = ArrayOfCompatibleTraits>({
  client,
  args,
  options
}: CwInfuserInfusionGeneticsQuery<TData>) {
  return useQuery<ArrayOfCompatibleTraits, Error, TData>(cwInfuserQueryKeys.infusionGenetics(client?.contractAddress, args), () => client ? client.infusionGenetics({
    id: args.id
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserIsInBundleQuery<TData> extends CwInfuserReactQuery<Boolean, TData> {
  args: {
    collectionAddr: Addr;
    infusionId: number;
  };
}
export function useCwInfuserIsInBundleQuery<TData = Boolean>({
  client,
  args,
  options
}: CwInfuserIsInBundleQuery<TData>) {
  return useQuery<Boolean, Error, TData>(cwInfuserQueryKeys.isInBundle(client?.contractAddress, args), () => client ? client.isInBundle({
    collectionAddr: args.collectionAddr,
    infusionId: args.infusionId
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserInfusionsQuery<TData> extends CwInfuserReactQuery<InfusionsResponse, TData> {
  args: {
    addr: Addr;
    index: number;
  };
}
export function useCwInfuserInfusionsQuery<TData = InfusionsResponse>({
  client,
  args,
  options
}: CwInfuserInfusionsQuery<TData>) {
  return useQuery<InfusionsResponse, Error, TData>(cwInfuserQueryKeys.infusions(client?.contractAddress, args), () => client ? client.infusions({
    addr: args.addr,
    index: args.index
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserInfusionByIdQuery<TData> extends CwInfuserReactQuery<InfusionState, TData> {
  args: {
    id: number;
  };
}
export function useCwInfuserInfusionByIdQuery<TData = InfusionState>({
  client,
  args,
  options
}: CwInfuserInfusionByIdQuery<TData>) {
  return useQuery<InfusionState, Error, TData>(cwInfuserQueryKeys.infusionById(client?.contractAddress, args), () => client ? client.infusionById({
    id: args.id
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserInfusionQuery<TData> extends CwInfuserReactQuery<Infusion, TData> {
  args: {
    addr: Addr;
    id: number;
  };
}
export function useCwInfuserInfusionQuery<TData = Infusion>({
  client,
  args,
  options
}: CwInfuserInfusionQuery<TData>) {
  return useQuery<Infusion, Error, TData>(cwInfuserQueryKeys.infusion(client?.contractAddress, args), () => client ? client.infusion({
    addr: args.addr,
    id: args.id
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface CwInfuserConfigQuery<TData> extends CwInfuserReactQuery<Config, TData> {}
export function useCwInfuserConfigQuery<TData = Config>({
  client,
  options
}: CwInfuserConfigQuery<TData>) {
  return useQuery<Config, Error, TData>(cwInfuserQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}