// Auto-generated by gen-tools.
// Do not edit manually.

/** A human readable address.

In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.

This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.

This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance. */
export type Addr = string;

export interface BlendNFTs {
  addr: Addr;
  min_req: number;
  payment_substitute: boolean;
}

export interface Bundle {
  nfts: NFT[];
}

export interface BundleBlend {
  blend_nfts: BlendNFTs[];
}

export type BundleType =
  | { all_of: Record<string, unknown> } |
  | { any_of: { addrs: Addr[] } } |
  | { any_of_blend: { blends: BundleBlend[] } };

export interface BurnParams {
  compatible_traits: CompatibleTraits[];
}

export interface Coin {
  amount: Uint128;
  denom: string;
}

export interface CompatibleTraits {
  a: string;
  b: string;
}

/** A fixed-point decimal value with 18 fractional digits, i.e. Decimal(1_000_000_000_000_000_000) == 1.0

The greatest possible value that can be represented is 340282366920938463463.374607431768211455 (which is (2^128 - 1) / 10^18) */
export type Decimal = string;

export interface EligibleNFTCollection {
  /** collection address */
  addr: Addr;
  /** Optional, maximum tokens able to be infused. If not set, contract expects exact # of min_req per collection in bundle. */
  max_req?: unknown;
  /** Minimum tokens required to infuse */
  min_req: number;
  /** If set, infuser can send exact amount of tokens to replace eligil */
  payment_substitute?: Coin | null;
}

/** This is a wrapper around Vec<u8> to add hex de/serialization with serde. It also adds some helper methods to help encode inline.

This is similar to `cosmwasm_std::Binary` but uses hex. See also <https://github.com/CosmWasm/cosmwasm/blob/main/docs/MESSAGE_TYPES.md>. */
export type HexBinary = string;

export interface InfusedCollection {
  /** exists to reuse InfusedCollection struct in contract. value is disregarded if present in new infusion creation msg. */
  addr?: unknown;
  admin?: unknown;
  /** ipfs base uri containing metadata and nft images. ensure ipfs:// prefix is included. */
  base_uri: string;
  /** infused collection description */
  description: string;
  /** whether explicit content is present. */
  explicit_content?: unknown;
  /** optional external link. */
  external_link?: unknown;
  /** cover image of infused collection. */
  image: string;
  name: string;
  /** total supply. */
  num_tokens: number;
  /** royality params for secondary market sales. */
  royalty_info?: RoyaltyInfoResponse | null;
  sg: boolean;
  /** time in which trading can begin of infused collection. */
  start_trading_time?: Timestamp | null;
  /** symbol of infused collection */
  symbol: string;
}

export interface Infusion {
  /** NFT collections eligible for a specific infusion */
  collections: EligibleNFTCollection[];
  /** Optional description of this infusion */
  description?: unknown;
  /** Current data of the new infused collection */
  infused_collection: InfusedCollection;
  /** Parameters of a specific infusion */
  infusion_params: InfusionParamState;
  /** Owner of the infusion. */
  owner?: Addr | null;
  payment_recipient?: Addr | null;
}

export interface InfusionParamState {
  bundle_type: BundleType;
  /** required alongside a bundle. Sent to infusion owner */
  mint_fee?: Coin | null;
  params?: BurnParams | null;
  wavs_enabled: boolean;
}

export interface InfusionState {
  /** NFT collections eligible for a specific infusion */
  collections: EligibleNFTCollection[];
  enabled: boolean;
  /** Current data of the new infused collection */
  infused_collection: InfusedCollection;
  /** Parameters of a specific infusion */
  infusion_params: InfusionParamState;
  owner: Addr;
  payment_recipient: Addr;
}

export interface NFT {
  addr: Addr;
  token_id: number;
}

export interface RoyaltyInfoResponse {
  payment_address: string;
  share: Decimal;
}

/** A point in time in nanosecond precision.

This type can represent times from 1970-01-01T00:00:00Z to 2554-07-21T23:34:33Z.

## Examples

``` # use cosmwasm_std::Timestamp; let ts = Timestamp::from_nanos(1_000_000_202); assert_eq!(ts.nanos(), 1_000_000_202); assert_eq!(ts.seconds(), 1); assert_eq!(ts.subsec_nanos(), 202);

let ts = ts.plus_seconds(2); assert_eq!(ts.nanos(), 3_000_000_202); assert_eq!(ts.seconds(), 3); assert_eq!(ts.subsec_nanos(), 202); ``` */
export type Timestamp = unknown;

/** A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `from` to create instances of this and `u128` to get the value out:

``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);

let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);

let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ``` */
export type Uint128 = string;

/** A thin wrapper around u64 that is using strings for JSON encoding/decoding, such that the full u64 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `from` to create instances of this and `u64` to get the value out:

``` # use cosmwasm_std::Uint64; let a = Uint64::from(42u64); assert_eq!(a.u64(), 42);

let b = Uint64::from(70u32); assert_eq!(b.u64(), 70); ``` */
export type Uint64 = string;

export interface UpdateInfusion {
  infused_collection_state?: unknown;
  /** Owner of the infusion. Optional description of this infusion */
  infusion_description?: unknown;
  owner?: Addr | null;
  payment_recipient?: Addr | null;
}

export interface UpdatingConfig {
  code_id?: unknown;
  contract_owner?: unknown;
  max_bundles?: unknown;
  max_infusions?: unknown;
  min_creation_fee?: Coin | null;
  min_infusion_fee?: Coin | null;
  min_per_bundle?: unknown;
  owner_fee?: Decimal | null;
}

export interface WavsBundle {
  /** nft-id's of nfts that were infused */
  infused_ids: string[];
  /** Address of the account that infused the nfts */
  infuser: string;
  /** Address of nft that was infused */
  nft_addr: string;
}

/** An bech32 address and its burn count */
export interface WavsRecordResponse {
  addr: string;
  count?: unknown;
}

export interface InstantiateMsg {
  /** owner of this contract */
  contract_owner?: unknown;
  /** Code-ID of the cw721-collection */
  cw721_code_id: number;
  /** Maximum bundles any infusion is able to require */
  max_bundles?: unknown;
  /** Maximum infusions that may be created at once */
  max_infusions?: unknown;
  /** Maximim tokens required for any infusions eligible collections */
  max_per_bundle?: unknown;
  /** Minimum fee that is required for creating an infusion */
  min_creation_fee?: Coin | null;
  /** Minimum fee that is required to be set when infusions occur */
  min_infusion_fee?: Coin | null;
  /** Minimum tokens required for any infusions eligible collections */
  min_per_bundle?: unknown;
  /** Fee from each infusion payment, if required. Goes to contract owner during any infusion. Set to 0.0 to disable. */
  owner_fee: Decimal;
  /** Optional key wavs operators make use of, if support is enabled */
  wavs_public_key?: unknown;
}

export type ExecuteMsg =
  | { create_infusion: { infusions: Infusion[] } } |
  | { wavs_entry_point: { infusions: WavsBundle[] } } |
  | { infuse: { bundle: Bundle[]; id: number } } |
  | { end_infusion: { id: number } } |
  | { update_infusion_base_uri: { base_uri: string; id: number } } |
  | { update_config: { config: UpdatingConfig } } |
  | { update_infusions_eligible_collections_or_bundle_type: { bundle_type: BundleType; id: number; to_add: EligibleNFTCollection[]; to_remove: Addr[] } } |
  | { update_infusion_mint_fee: { id: number; mint_fee: Coin | null } } |
  | { update_infusion_params: { id: number; params: UpdateInfusion } } |
  | { shuffle: { id: number } };

export type QueryMsg =
  | { config: Record<string, unknown> } |
  | { infusion: { addr: Addr; id: number } } |
  | { infusion_by_id: { id: number } } |
  | { infusions: { addr: Addr; index: number } } |
  | { infusion_genetics: { id: number } } |
  | { wavs_record: { burner: Addr | null; nfts: string[] } };

/** map of infusion */
export interface Config {
  /** code hash of cw721. used for instantitate2 during infusion creation. */
  code_hash: HexBinary;
  /** cw721-base code_id */
  code_id: number;
  contract_owner: Addr;
  latest_infusion_id: number;
  /** maximum bundles allowed per infusion */
  max_bundles: number;
  /** Maximum unique infusion that can be created at once. Defaults to 2 */
  max_infusions: number;
  /** Contract global param enforcing maximum nfts bundles can require. */
  max_per_bundle: number;
  /** Minimum fee that is required for creating an infusion. */
  min_creation_fee?: Coin | null;
  /** Minimum fee that is required to be set when new infusions are being created */
  min_infusion_fee?: Coin | null;
  /** Contract global param enforcing minimum nfts each collection in an infusion must require to burn. hard coded to 1. */
  min_per_bundle: number;
  /** Fee required to contribute to randomness % Fee from any infusion fee set to go to contract owner. 10 == 10% , 71 == 71% */
  owner_fee: Decimal;
}

export interface InfusionsResponse {
  infusions: InfusionState[];
}

