/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { Uint128, Decimal, InstantiateMsg, Coin, ExecuteMsg, Addr, Timestamp, Uint64, BundleType, Infusion, EligibleNFTCollection, InfusedCollection, RoyaltyInfoResponse, InfusionParamState, BundleBlend, BlendNFTs, BurnParams, CompatibleTraits, WavsBundle, Bundle, NFT, UpdatingConfig, UpdateInfusion, QueryMsg, HexBinary, Config, InfusionState, ArrayOfCompatibleTraits, InfusionsResponse, ArrayOfWavsRecordResponse, WavsRecordResponse } from "./CwInfusionMinter.types";
export interface CwInfusionMinterMsg {
  contractAddress: string;
  sender: string;
  createInfusion: ({
    infusions
  }: {
    infusions: Infusion[];
  }, funds_?: Coin[]) => EncodeObject;
  wavsEntryPoint: ({
    infusions
  }: {
    infusions: WavsBundle[];
  }, funds_?: Coin[]) => EncodeObject;
  infuse: ({
    bundle,
    id
  }: {
    bundle: Bundle[];
    id: number;
  }, funds_?: Coin[]) => EncodeObject;
  endInfusion: ({
    id
  }: {
    id: number;
  }, funds_?: Coin[]) => EncodeObject;
  updateInfusionBaseUri: ({
    baseUri,
    id
  }: {
    baseUri: string;
    id: number;
  }, funds_?: Coin[]) => EncodeObject;
  updateConfig: ({
    config
  }: {
    config: UpdatingConfig;
  }, funds_?: Coin[]) => EncodeObject;
  updateInfusionsEligibleCollectionsOrBundleType: ({
    bundleType,
    id,
    toAdd,
    toRemove
  }: {
    bundleType: BundleType;
    id: number;
    toAdd: EligibleNFTCollection[];
    toRemove: Addr[];
  }, funds_?: Coin[]) => EncodeObject;
  updateInfusionMintFee: ({
    id,
    mintFee
  }: {
    id: number;
    mintFee?: Coin;
  }, funds_?: Coin[]) => EncodeObject;
  updateInfusionParams: ({
    id,
    params
  }: {
    id: number;
    params: UpdateInfusion;
  }, funds_?: Coin[]) => EncodeObject;
  shuffle: ({
    id
  }: {
    id: number;
  }, funds_?: Coin[]) => EncodeObject;
}
export class CwInfusionMinterMsgComposer implements CwInfusionMinterMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createInfusion = this.createInfusion.bind(this);
    this.wavsEntryPoint = this.wavsEntryPoint.bind(this);
    this.infuse = this.infuse.bind(this);
    this.endInfusion = this.endInfusion.bind(this);
    this.updateInfusionBaseUri = this.updateInfusionBaseUri.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updateInfusionsEligibleCollectionsOrBundleType = this.updateInfusionsEligibleCollectionsOrBundleType.bind(this);
    this.updateInfusionMintFee = this.updateInfusionMintFee.bind(this);
    this.updateInfusionParams = this.updateInfusionParams.bind(this);
    this.shuffle = this.shuffle.bind(this);
  }
  createInfusion = ({
    infusions
  }: {
    infusions: Infusion[];
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_infusion: {
            infusions
          }
        })),
        funds: funds_
      })
    };
  };
  wavsEntryPoint = ({
    infusions
  }: {
    infusions: WavsBundle[];
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          wavs_entry_point: {
            infusions
          }
        })),
        funds: funds_
      })
    };
  };
  infuse = ({
    bundle,
    id
  }: {
    bundle: Bundle[];
    id: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          infuse: {
            bundle,
            id
          }
        })),
        funds: funds_
      })
    };
  };
  endInfusion = ({
    id
  }: {
    id: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          end_infusion: {
            id
          }
        })),
        funds: funds_
      })
    };
  };
  updateInfusionBaseUri = ({
    baseUri,
    id
  }: {
    baseUri: string;
    id: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_infusion_base_uri: {
            base_uri: baseUri,
            id
          }
        })),
        funds: funds_
      })
    };
  };
  updateConfig = ({
    config
  }: {
    config: UpdatingConfig;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            config
          }
        })),
        funds: funds_
      })
    };
  };
  updateInfusionsEligibleCollectionsOrBundleType = ({
    bundleType,
    id,
    toAdd,
    toRemove
  }: {
    bundleType: BundleType;
    id: number;
    toAdd: EligibleNFTCollection[];
    toRemove: Addr[];
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_infusions_eligible_collections_or_bundle_type: {
            bundle_type: bundleType,
            id,
            to_add: toAdd,
            to_remove: toRemove
          }
        })),
        funds: funds_
      })
    };
  };
  updateInfusionMintFee = ({
    id,
    mintFee
  }: {
    id: number;
    mintFee?: Coin;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_infusion_mint_fee: {
            id,
            mint_fee: mintFee
          }
        })),
        funds: funds_
      })
    };
  };
  updateInfusionParams = ({
    id,
    params
  }: {
    id: number;
    params: UpdateInfusion;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_infusion_params: {
            id,
            params
          }
        })),
        funds: funds_
      })
    };
  };
  shuffle = ({
    id
  }: {
    id: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          shuffle: {
            id
          }
        })),
        funds: funds_
      })
    };
  };
}