// Auto-generated by gen-tools.
import type { CwInfuser as CwInfuserType } from './CwInfuser.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface CwInfuserQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

  config(params: Extract<CwInfuserType, { config: unknown }>['config']): Promise<Config>;
  infusion(params: Extract<CwInfuserType, { infusion: unknown }>['infusion']): Promise<Infusion>;
  infusionById(params: Extract<CwInfuserType, { infusion_by_id: unknown }>['infusion_by_id']): Promise<unknown>;
  infusions(params: Extract<CwInfuserType, { infusions: unknown }>['infusions']): Promise<unknown>;
  isInBundle(params: Extract<CwInfuserType, { is_in_bundle: unknown }>['is_in_bundle']): Promise<unknown>;
  infusionGenetics(params: Extract<CwInfuserType, { infusion_genetics: unknown }>['infusion_genetics']): Promise<unknown>;
  wavsRecord(params: Extract<CwInfuserType, { wavs_record: unknown }>['wavs_record']): Promise<unknown>;
}

export interface CwInfuserExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

  createInfusion(params: Extract<CwInfuserType, { create_infusion: unknown }>['create_infusion']): Promise<string>;
  wavsEntryPoint(params: Extract<CwInfuserType, { wavs_entry_point: unknown }>['wavs_entry_point']): Promise<string>;
  infuse(params: Extract<CwInfuserType, { infuse: unknown }>['infuse']): Promise<string>;
  endInfusion(params: Extract<CwInfuserType, { end_infusion: unknown }>['end_infusion']): Promise<string>;
  updateInfusionBaseUri(params: Extract<CwInfuserType, { update_infusion_base_uri: unknown }>['update_infusion_base_uri']): Promise<string>;
  updateConfig(params: Extract<CwInfuserType, { update_config: unknown }>['update_config']): Promise<string>;
  updateInfusionsEligibleCollections(params: Extract<CwInfuserType, { update_infusions_eligible_collections: unknown }>['update_infusions_eligible_collections']): Promise<string>;
  updateInfusionMintFee(params: Extract<CwInfuserType, { update_infusion_mint_fee: unknown }>['update_infusion_mint_fee']): Promise<string>;
  updateInfusionBundleType(params: Extract<CwInfuserType, { update_infusion_bundle_type: unknown }>['update_infusion_bundle_type']): Promise<string>;
  shuffle(params: Extract<CwInfuserType, { shuffle: unknown }>['shuffle']): Promise<string>;
}
