// Auto-generated by gen-tools.
// Do not edit manually.

/** Actions that can be taken to alter the contract's ownership */
export type Action =
  | { transfer_ownership: { expiry: Expiration | null; new_owner: string } } |
  | 'accept_ownership' |
  | 'renounce_ownership';

/** A human readable address.

In Cosmos, this is typically bech32 encoded. But for multi-chain smart contracts no assumptions should be made other than being UTF-8 encoded and of reasonable length.

This type represents a validated address. It can be created in the following ways 1. Use `Addr::unchecked(input)` 2. Use `let checked: Addr = deps.api.addr_validate(input)?` 3. Use `let checked: Addr = deps.api.addr_humanize(canonical_addr)?` 4. Deserialize from JSON. This must only be done from JSON that was validated before such as a contract's state. `Addr` must not be used in messages sent by the user because this would result in unvalidated instances.

This type is immutable. If you really need to mutate it (Really? Are you sure?), create a mutable copy using `let mut mutable = Addr::to_string()` and operate on that `String` instance. */
export type Addr = string;

/** Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.

This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>. See also <https://github.com/CosmWasm/cosmwasm/blob/main/docs/MESSAGE_TYPES.md>. */
export type Binary = string;

export interface Coin {
  amount: Uint128;
  denom: string;
}

/** Expiration represents a point in time when some event happens. It can compare with a BlockInfo and will return is_expired() == true once the condition is hit (and for every block in the future) */
export type Expiration =
  | { at_height: number } |
  | { at_time: Timestamp } |
  | { never: Record<string, unknown> };

export interface InstantiateMsg {
  mint_end_time?: unknown;
  mint_start_time?: unknown;
  name: string;
  owner?: unknown;
  /** Address to receive mint payments. Defaults to owner/sender. */
  payment_address?: unknown;
  /** Price tiers for minting. Empty or None = free mint. */
  price_tiers: PriceTier[];
  seed: Binary;
  svg_template: string;
  symbol: string;
  /** Pre-computed placeholder positions in the SVG template. Each slot maps a `${varname}` occurrence to its byte offsets and variable index. */
  template_slots: TemplateSlot[];
  total: number;
  variables: VariableDef[];
  /** Optional merkle whitelist contract address. Whitelisted minters bypass fees. */
  whitelist?: unknown;
}

/** A price tier that applies until the mint count reaches `until_count`. Tiers must be sorted ascending by `until_count`. Example: [{ until_count: 100, price: 1_000_000utoken }, { until_count: 500, price: 5_000_000utoken }] means: first 100 mints cost 1 token, mints 101-500 cost 5 tokens. */
export interface PriceTier {
  /** Price per token in this tier */
  price: Coin;
  /** This tier applies while mint_count < until_count */
  until_count: number;
}

export interface RgbRange {
  b_max: number;
  b_min: number;
  g_max: number;
  g_min: number;
  r_max: number;
  r_min: number;
}

export interface SvgCollection {
  /** The instantiated collection contract address (primary key). */
  contract: string;
  /** Address that created this collection. */
  creator: string;
  /** Collection name from InstantiateMsg. */
  name: string;
  /** Collection symbol from InstantiateMsg. */
  symbol: string;
}

export interface TemplateSlot {
  end: number;
  start: number;
  var_idx: number;
}

/** A point in time in nanosecond precision.

This type can represent times from 1970-01-01T00:00:00Z to 2554-07-21T23:34:33Z.

## Examples

``` # use cosmwasm_std::Timestamp; let ts = Timestamp::from_nanos(1_000_000_202); assert_eq!(ts.nanos(), 1_000_000_202); assert_eq!(ts.seconds(), 1); assert_eq!(ts.subsec_nanos(), 202);

let ts = ts.plus_seconds(2); assert_eq!(ts.nanos(), 3_000_000_202); assert_eq!(ts.seconds(), 3); assert_eq!(ts.subsec_nanos(), 202); ``` */
export type Timestamp = unknown;

/** A thin wrapper around u128 that is using strings for JSON encoding/decoding, such that the full u128 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `from` to create instances of this and `u128` to get the value out:

``` # use cosmwasm_std::Uint128; let a = Uint128::from(123u128); assert_eq!(a.u128(), 123);

let b = Uint128::from(42u64); assert_eq!(b.u128(), 42);

let c = Uint128::from(70u32); assert_eq!(c.u128(), 70); ``` */
export type Uint128 = string;

/** A thin wrapper around u64 that is using strings for JSON encoding/decoding, such that the full u64 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `from` to create instances of this and `u64` to get the value out:

``` # use cosmwasm_std::Uint64; let a = Uint64::from(42u64); assert_eq!(a.u64(), 42);

let b = Uint64::from(70u32); assert_eq!(b.u64(), 70); ``` */
export type Uint64 = string;

export interface VariableDef {
  kind: VariableKind;
  name: string;
}

export type VariableKind =
  | { options: string[] } |
  | { range: { max: string; min: string; precision: number } } |
  | 'rgb' |
  | { rgb_styled: RgbRange[] };

export type ExecuteMsg =
  | { create_svg_collection: { instantiate_msg: InstantiateMsg; label: string } } |
  | { update_code_id: { code_id: number } } |
  | { update_ownership: Action };

export type QueryMsg =
  | { list_svg_collections: { limit: unknown; start_after: unknown } } |
  | { list_svg_collections_reverse: { limit: unknown; start_before: unknown } } |
  | { list_svg_collections_by_creator: { creator: string; limit: unknown; start_after: unknown } } |
  | { list_svg_collections_by_creator_reverse: { creator: string; limit: unknown; start_before: unknown } } |
  | { ownership: Record<string, unknown> } |
  | { code_id: Record<string, unknown> };

/** The contract's ownership info */
export interface OwnershipForAddr {
  /** The contract's current owner. `None` if the ownership has been renounced. */
  owner?: Addr | null;
  /** The deadline for the pending owner to accept the ownership. `None` if there isn't a pending ownership transfer, or if a transfer exists and it doesn't have a deadline. */
  pending_expiry?: Expiration | null;
  /** The account who has been proposed to take over the ownership. `None` if there isn't a pending ownership transfer. */
  pending_owner?: Addr | null;
}

