// Auto-generated by gen-tools.
import type { CwSvgMinter as CwSvgMinterType } from './CwSvgMinter.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface CwSvgMinterQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

  listSvgCollections(params: Extract<CwSvgMinterType, { list_svg_collections: unknown }>['list_svg_collections']): Promise<unknown>;
  listSvgCollectionsReverse(params: Extract<CwSvgMinterType, { list_svg_collections_reverse: unknown }>['list_svg_collections_reverse']): Promise<unknown>;
  listSvgCollectionsByCreator(params: Extract<CwSvgMinterType, { list_svg_collections_by_creator: unknown }>['list_svg_collections_by_creator']): Promise<unknown>;
  listSvgCollectionsByCreatorReverse(params: Extract<CwSvgMinterType, { list_svg_collections_by_creator_reverse: unknown }>['list_svg_collections_by_creator_reverse']): Promise<unknown>;
  ownership(params: Extract<CwSvgMinterType, { ownership: unknown }>['ownership']): Promise<unknown>;
  codeId(params: Extract<CwSvgMinterType, { code_id: unknown }>['code_id']): Promise<unknown>;
}

export interface CwSvgMinterExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

  createSvgCollection(params: Extract<CwSvgMinterType, { create_svg_collection: unknown }>['create_svg_collection']): Promise<string>;
  updateCodeId(params: Extract<CwSvgMinterType, { update_code_id: unknown }>['update_code_id']): Promise<string>;
  updateOwnership(params: Extract<CwSvgMinterType, { update_ownership: unknown }>['update_ownership']): Promise<string>;
}
