/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, VariableKind, Action, Expiration, Timestamp, Uint64, PriceTier, Coin, TemplateSlot, VariableDef, RgbRange, QueryMsg, ArrayOfSvgCollection, SvgCollection, Addr, OwnershipForAddr } from "./CwSvgMinter.types";
export interface CwSvgMinterMsg {
  contractAddress: string;
  sender: string;
  createSvgCollection: ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, funds_?: Coin[]) => EncodeObject;
  updateCodeId: ({
    codeId
  }: {
    codeId: number;
  }, funds_?: Coin[]) => EncodeObject;
  updateOwnership: (action: Action, funds_?: Coin[]) => EncodeObject;
}
export class CwSvgMinterMsgComposer implements CwSvgMinterMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createSvgCollection = this.createSvgCollection.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  createSvgCollection = ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_svg_collection: {
            instantiate_msg: instantiateMsg,
            label
          }
        })),
        funds: funds_
      })
    };
  };
  updateCodeId = ({
    codeId
  }: {
    codeId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_code_id: {
            code_id: codeId
          }
        })),
        funds: funds_
      })
    };
  };
  updateOwnership = (action: Action, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_ownership: action
        })),
        funds: funds_
      })
    };
  };
}