/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  mint_end_time?: number | null;
  mint_start_time?: number | null;
  name: string;
  owner?: string | null;
  payment_address?: string | null;
  price_tiers: PriceTier[];
  seed: Binary;
  svg_template: string;
  symbol: string;
  template_slots: TemplateSlot[];
  total: number;
  variables: VariableDef[];
  whitelist?: string | null;
}
export type ExecuteMsg = {
  create_svg_collection: {
    instantiate_msg: InstantiateMsg;
    label: string;
  };
} | {
  update_code_id: {
    code_id: number;
  };
} | {
  update_ownership: Action;
};
export type Uint128 = string;
export type Binary = string;
export type VariableKind = {
  options: string[];
} | {
  range: {
    max: string;
    min: string;
    precision: number;
  };
} | "rgb" | {
  rgb_styled: RgbRange[];
};
export type Action = {
  transfer_ownership: {
    expiry?: Expiration | null;
    new_owner: string;
  };
} | "accept_ownership" | "renounce_ownership";
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {};
};
export type Timestamp = Uint64;
export type Uint64 = string;
export interface PriceTier {
  price: Coin;
  until_count: number;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface TemplateSlot {
  end: number;
  start: number;
  var_idx: number;
}
export interface VariableDef {
  kind: VariableKind;
  name: string;
}
export interface RgbRange {
  b_max: number;
  b_min: number;
  g_max: number;
  g_min: number;
  r_max: number;
  r_min: number;
}
export type QueryMsg = {
  list_svg_collections: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  list_svg_collections_reverse: {
    limit?: number | null;
    start_before?: string | null;
  };
} | {
  list_svg_collections_by_creator: {
    creator: string;
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  list_svg_collections_by_creator_reverse: {
    creator: string;
    limit?: number | null;
    start_before?: string | null;
  };
} | {
  ownership: {};
} | {
  code_id: {};
};
export type ArrayOfSvgCollection = SvgCollection[];
export interface SvgCollection {
  contract: string;
  creator: string;
  name: string;
  symbol: string;
}
export type Addr = string;
export interface OwnershipForAddr {
  owner?: Addr | null;
  pending_expiry?: Expiration | null;
  pending_owner?: Addr | null;
}