/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, VariableKind, Action, Expiration, Timestamp, Uint64, PriceTier, Coin, TemplateSlot, VariableDef, RgbRange, QueryMsg, ArrayOfSvgCollection, SvgCollection, Addr, OwnershipForAddr } from "./CwSvgMinter.types";
export interface CwSvgMinterReadOnlyInterface {
  contractAddress: string;
  listSvgCollections: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfSvgCollection>;
  listSvgCollectionsReverse: ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfSvgCollection>;
  listSvgCollectionsByCreator: ({
    creator,
    limit,
    startAfter
  }: {
    creator: string;
    limit?: number;
    startAfter?: string;
  }) => Promise<ArrayOfSvgCollection>;
  listSvgCollectionsByCreatorReverse: ({
    creator,
    limit,
    startBefore
  }: {
    creator: string;
    limit?: number;
    startBefore?: string;
  }) => Promise<ArrayOfSvgCollection>;
  ownership: () => Promise<OwnershipForAddr>;
  codeId: () => Promise<Uint64>;
}
export class CwSvgMinterQueryClient implements CwSvgMinterReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.listSvgCollections = this.listSvgCollections.bind(this);
    this.listSvgCollectionsReverse = this.listSvgCollectionsReverse.bind(this);
    this.listSvgCollectionsByCreator = this.listSvgCollectionsByCreator.bind(this);
    this.listSvgCollectionsByCreatorReverse = this.listSvgCollectionsByCreatorReverse.bind(this);
    this.ownership = this.ownership.bind(this);
    this.codeId = this.codeId.bind(this);
  }
  listSvgCollections = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfSvgCollection> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_svg_collections: {
        limit,
        start_after: startAfter
      }
    });
  };
  listSvgCollectionsReverse = async ({
    limit,
    startBefore
  }: {
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfSvgCollection> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_svg_collections_reverse: {
        limit,
        start_before: startBefore
      }
    });
  };
  listSvgCollectionsByCreator = async ({
    creator,
    limit,
    startAfter
  }: {
    creator: string;
    limit?: number;
    startAfter?: string;
  }): Promise<ArrayOfSvgCollection> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_svg_collections_by_creator: {
        creator,
        limit,
        start_after: startAfter
      }
    });
  };
  listSvgCollectionsByCreatorReverse = async ({
    creator,
    limit,
    startBefore
  }: {
    creator: string;
    limit?: number;
    startBefore?: string;
  }): Promise<ArrayOfSvgCollection> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_svg_collections_by_creator_reverse: {
        creator,
        limit,
        start_before: startBefore
      }
    });
  };
  ownership = async (): Promise<OwnershipForAddr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      ownership: {}
    });
  };
  codeId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      code_id: {}
    });
  };
}
export interface CwSvgMinterInterface extends CwSvgMinterReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createSvgCollection: ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateCodeId: ({
    codeId
  }: {
    codeId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateOwnership: (action: Action, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class CwSvgMinterClient extends CwSvgMinterQueryClient implements CwSvgMinterInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createSvgCollection = this.createSvgCollection.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateOwnership = this.updateOwnership.bind(this);
  }
  createSvgCollection = async ({
    instantiateMsg,
    label
  }: {
    instantiateMsg: InstantiateMsg;
    label: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_svg_collection: {
        instantiate_msg: instantiateMsg,
        label
      }
    }, fee_, memo_, funds_);
  };
  updateCodeId = async ({
    codeId
  }: {
    codeId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_code_id: {
        code_id: codeId
      }
    }, fee_, memo_, funds_);
  };
  updateOwnership = async (action: Action, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_ownership: action
    }, fee_, memo_, funds_);
  };
}