// Auto-generated by gen-tools.
import type { CwSvgMinter } from './CwSvgMinter.types';
import type { Coin } from '@cosmjs/amino';
import type { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

export class CwSvgMinterMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

  createSvgCollection(msg: Extract<CwSvgMinterType, { create_svg_collection: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateCodeId(msg: Extract<CwSvgMinterType, { update_code_id: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  updateOwnership(msg: Extract<CwSvgMinterType, { update_ownership: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

}
