/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { EventSupplierType, InstantiateMsg, GroupInit, EventSupplierInit, ExecuteMsg, Timestamp, Uint64, CosmosMsgForEmpty, BankMsg, Uint128, StakingMsg, DistributionMsg, Binary, IbcMsg, WasmMsg, GovMsg, VoteOption, Decimal, Empty, EventServiceInit, Coin, AnyMsg, IbcTimeout, IbcTimeoutBlock, IbcAcknowledgement, IbcFee, WeightedVoteOption, QueryMsg, EventFilter, EventStatus, MigrateMsg, Addr, DumpStateResponse, ContractVersion, Group, EventSupplier, EventResponseForEmpty, EventForEmpty, EventService, EventGaugeResponse, GroupGaugeSummary, GaugeConfig, HooksResponse, GroupResponse, GroupsManagingEventResponse, InfoResponse, EventListResponseForEmpty, GroupListResponse } from "./DaoCalendar.types";
export interface DaoCalendarMsg {
  contractAddress: string;
  sender: string;
  createEvent: ({
    description,
    endTime,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime: Timestamp;
    extension?: Empty;
    managingGroups: string[];
    services?: EventServiceInit[];
    startTime: Timestamp;
    title: string;
  }, funds_?: Coin[]) => EncodeObject;
  updateEvent: ({
    description,
    endTime,
    eventId,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime?: Timestamp;
    eventId: number;
    extension?: Empty;
    managingGroups?: string[];
    services?: EventServiceInit[];
    startTime?: Timestamp;
    title?: string;
  }, funds_?: Coin[]) => EncodeObject;
  cancelEvent: ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]) => EncodeObject;
  registerEventGauges: ({
    beginMsgs,
    endMsgs,
    eventId
  }: {
    beginMsgs: CosmosMsgForEmpty[];
    endMsgs: CosmosMsgForEmpty[];
    eventId: number;
  }, funds_?: Coin[]) => EncodeObject;
  triggerEventStart: ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]) => EncodeObject;
  triggerEventEnd: ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]) => EncodeObject;
  registerGroup: ({
    group
  }: {
    group: GroupInit;
  }, funds_?: Coin[]) => EncodeObject;
  updateGroup: ({
    groupId,
    suppliers
  }: {
    groupId: string;
    suppliers?: EventSupplierInit[];
  }, funds_?: Coin[]) => EncodeObject;
  removeGroup: ({
    groupId
  }: {
    groupId: string;
  }, funds_?: Coin[]) => EncodeObject;
  renewCalendar: ({
    limit
  }: {
    limit?: number;
  }, funds_?: Coin[]) => EncodeObject;
  addEventHook: ({
    address
  }: {
    address: string;
  }, funds_?: Coin[]) => EncodeObject;
  removeEventHook: ({
    address
  }: {
    address: string;
  }, funds_?: Coin[]) => EncodeObject;
}
export class DaoCalendarMsgComposer implements DaoCalendarMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createEvent = this.createEvent.bind(this);
    this.updateEvent = this.updateEvent.bind(this);
    this.cancelEvent = this.cancelEvent.bind(this);
    this.registerEventGauges = this.registerEventGauges.bind(this);
    this.triggerEventStart = this.triggerEventStart.bind(this);
    this.triggerEventEnd = this.triggerEventEnd.bind(this);
    this.registerGroup = this.registerGroup.bind(this);
    this.updateGroup = this.updateGroup.bind(this);
    this.removeGroup = this.removeGroup.bind(this);
    this.renewCalendar = this.renewCalendar.bind(this);
    this.addEventHook = this.addEventHook.bind(this);
    this.removeEventHook = this.removeEventHook.bind(this);
  }
  createEvent = ({
    description,
    endTime,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime: Timestamp;
    extension?: Empty;
    managingGroups: string[];
    services?: EventServiceInit[];
    startTime: Timestamp;
    title: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_event: {
            description,
            end_time: endTime,
            extension,
            managing_groups: managingGroups,
            services,
            start_time: startTime,
            title
          }
        })),
        funds: funds_
      })
    };
  };
  updateEvent = ({
    description,
    endTime,
    eventId,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime?: Timestamp;
    eventId: number;
    extension?: Empty;
    managingGroups?: string[];
    services?: EventServiceInit[];
    startTime?: Timestamp;
    title?: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_event: {
            description,
            end_time: endTime,
            event_id: eventId,
            extension,
            managing_groups: managingGroups,
            services,
            start_time: startTime,
            title
          }
        })),
        funds: funds_
      })
    };
  };
  cancelEvent = ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          cancel_event: {
            event_id: eventId
          }
        })),
        funds: funds_
      })
    };
  };
  registerEventGauges = ({
    beginMsgs,
    endMsgs,
    eventId
  }: {
    beginMsgs: CosmosMsgForEmpty[];
    endMsgs: CosmosMsgForEmpty[];
    eventId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_event_gauges: {
            begin_msgs: beginMsgs,
            end_msgs: endMsgs,
            event_id: eventId
          }
        })),
        funds: funds_
      })
    };
  };
  triggerEventStart = ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          trigger_event_start: {
            event_id: eventId
          }
        })),
        funds: funds_
      })
    };
  };
  triggerEventEnd = ({
    eventId
  }: {
    eventId: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          trigger_event_end: {
            event_id: eventId
          }
        })),
        funds: funds_
      })
    };
  };
  registerGroup = ({
    group
  }: {
    group: GroupInit;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          register_group: {
            group
          }
        })),
        funds: funds_
      })
    };
  };
  updateGroup = ({
    groupId,
    suppliers
  }: {
    groupId: string;
    suppliers?: EventSupplierInit[];
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_group: {
            group_id: groupId,
            suppliers
          }
        })),
        funds: funds_
      })
    };
  };
  removeGroup = ({
    groupId
  }: {
    groupId: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_group: {
            group_id: groupId
          }
        })),
        funds: funds_
      })
    };
  };
  renewCalendar = ({
    limit
  }: {
    limit?: number;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          renew_calendar: {
            limit
          }
        })),
        funds: funds_
      })
    };
  };
  addEventHook = ({
    address
  }: {
    address: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          add_event_hook: {
            address
          }
        })),
        funds: funds_
      })
    };
  };
  removeEventHook = ({
    address
  }: {
    address: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_event_hook: {
            address
          }
        })),
        funds: funds_
      })
    };
  };
}