/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type EventSupplierType = "authorization" | "gauge" | "service" | "account";
export interface InstantiateMsg {
  initial_groups?: GroupInit[] | null;
}
export interface GroupInit {
  id: string;
  suppliers: EventSupplierInit[];
}
export interface EventSupplierInit {
  contract: string;
  supplier_type: EventSupplierType;
}
export type ExecuteMsg = {
  create_event: {
    description?: string | null;
    end_time: Timestamp;
    extension?: Empty | null;
    managing_groups: string[];
    services?: EventServiceInit[] | null;
    start_time: Timestamp;
    timezone?: string | null;
    recurrence?: RecurrenceRule | null;
    title: string;
  };
} | {
  update_event: {
    description?: string | null;
    end_time?: Timestamp | null;
    event_id: number;
    extension?: Empty | null;
    managing_groups?: string[] | null;
    services?: EventServiceInit[] | null;
    start_time?: Timestamp | null;
    timezone?: string | null;
    title?: string | null;
  };
} | {
  cancel_event: {
    event_id: number;
  };
} | {
  register_event_gauges: {
    begin_msgs: CosmosMsgForEmpty[];
    end_msgs: CosmosMsgForEmpty[];
    event_id: number;
  };
} | {
  trigger_event_start: {
    event_id: number;
  };
} | {
  trigger_event_end: {
    event_id: number;
  };
} | {
  register_group: {
    group: GroupInit;
  };
} | {
  update_group: {
    group_id: string;
    suppliers?: EventSupplierInit[] | null;
  };
} | {
  remove_group: {
    group_id: string;
  };
} | {
  renew_calendar: {
    limit?: number | null;
  };
} | {
  add_event_hook: {
    address: string;
  };
} | {
  remove_event_hook: {
    address: string;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type CosmosMsgForEmpty = {
  bank: BankMsg;
} | {
  custom: Empty;
} | {
  staking: StakingMsg;
} | {
  distribution: DistributionMsg;
} | {
  stargate: {
    type_url: string;
    value: Binary;
  };
} | {
  any: AnyMsg;
} | {
  ibc: IbcMsg;
} | {
  wasm: WasmMsg;
} | {
  gov: GovMsg;
};
export type BankMsg = {
  send: {
    amount: Coin[];
    to_address: string;
  };
} | {
  burn: {
    amount: Coin[];
  };
};
export type Uint128 = string;
export type StakingMsg = {
  delegate: {
    amount: Coin;
    validator: string;
  };
} | {
  undelegate: {
    amount: Coin;
    validator: string;
  };
} | {
  redelegate: {
    amount: Coin;
    dst_validator: string;
    src_validator: string;
  };
};
export type DistributionMsg = {
  set_withdraw_address: {
    address: string;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
  };
} | {
  fund_community_pool: {
    amount: Coin[];
  };
};
export type Binary = string;
export type IbcMsg = {
  transfer: {
    amount: Coin;
    channel_id: string;
    memo?: string | null;
    timeout: IbcTimeout;
    to_address: string;
  };
} | {
  send_packet: {
    channel_id: string;
    data: Binary;
    timeout: IbcTimeout;
  };
} | {
  write_acknowledgement: {
    ack: IbcAcknowledgement;
    channel_id: string;
    packet_sequence: number;
  };
} | {
  close_channel: {
    channel_id: string;
  };
} | {
  pay_packet_fee: {
    channel_id: string;
    fee: IbcFee;
    port_id: string;
    relayers: string[];
  };
} | {
  pay_packet_fee_async: {
    channel_id: string;
    fee: IbcFee;
    port_id: string;
    relayers: string[];
    sequence: number;
  };
};
export type WasmMsg = {
  execute: {
    contract_addr: string;
    funds: Coin[];
    msg: Binary;
  };
} | {
  instantiate: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
  };
} | {
  instantiate2: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    salt: Binary;
  };
} | {
  migrate: {
    contract_addr: string;
    msg: Binary;
    new_code_id: number;
  };
} | {
  update_admin: {
    admin: string;
    contract_addr: string;
  };
} | {
  clear_admin: {
    contract_addr: string;
  };
};
export type GovMsg = {
  vote: {
    option: VoteOption;
    proposal_id: number;
  };
} | {
  vote_weighted: {
    options: WeightedVoteOption[];
    proposal_id: number;
  };
};
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
export type Decimal = string;
export interface Empty {}
export type RecurrenceFrequency = "daily" | "weekly" | "monthly" | "yearly";
export type DayOfWeek = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
export type RecurrenceEnd = {
  never: {};
} | {
  after_count: number;
} | {
  at_date: Timestamp;
};
export interface RecurrenceRule {
  frequency: RecurrenceFrequency;
  interval: number;
  days_of_week?: DayOfWeek[] | null;
  end_condition: RecurrenceEnd;
}
export interface EventServiceInit {
  description?: string | null;
  msgs: CosmosMsgForEmpty[];
  name: string;
  target_contract?: string | null;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface AnyMsg {
  type_url: string;
  value: Binary;
}
export interface IbcTimeout {
  block?: IbcTimeoutBlock | null;
  timestamp?: Timestamp | null;
}
export interface IbcTimeoutBlock {
  height: number;
  revision: number;
}
export interface IbcAcknowledgement {
  data: Binary;
}
export interface IbcFee {
  ack_fee: Coin[];
  receive_fee: Coin[];
  timeout_fee: Coin[];
}
export interface WeightedVoteOption {
  option: VoteOption;
  weight: Decimal;
}
export type QueryMsg = {
  event: {
    event_id: number;
  };
} | {
  list_events: {
    filter?: EventFilter | null;
    limit?: number | null;
    start_after?: number | null;
  };
} | {
  reverse_events: {
    filter?: EventFilter | null;
    limit?: number | null;
    start_before?: number | null;
  };
} | {
  list_groups: {};
} | {
  group: {
    group_id: string;
  };
} | {
  groups_managing_event: {
    event_id: number;
  };
} | {
  event_gauges: {
    event_id: number;
  };
} | {
  event_count: {};
} | {
  event_hooks: {};
} | {
  dump_state: {};
} | {
  dao: {};
} | {
  info: {};
} | {
  next_proposal_id: {};
} | {
  agenda: {
    from?: Timestamp | null;
    limit?: number | null;
  };
};
export type EventFilter = {
  by_groups: {
    groups: string[];
  };
} | {
  by_time_range: {
    end_before?: Timestamp | null;
    start_after?: Timestamp | null;
  };
} | {
  by_status: {
    status: EventStatus;
  };
};
export type EventStatus = "upcoming" | "active" | "completed" | "cancelled";
export type MigrateMsg = {
  from_compatible: {};
};
export type Addr = string;
export interface DumpStateResponse {
  contract_version: ContractVersion;
  dao: Addr;
  event_count: number;
  groups: Group[];
}
export interface ContractVersion {
  contract: string;
  version: string;
}
export interface Group {
  dao: Addr;
  id: string;
  suppliers: EventSupplier[];
  name: string;
  description?: string | null;
  color?: string | null;
  members?: string[] | null;
}
export interface EventSupplier {
  contract: Addr;
  supplier_type: EventSupplierType;
}
export interface EventResponseForEmpty {
  event: EventForEmpty;
  id: number;
}
export interface EventForEmpty {
  created_at: Timestamp;
  created_by: Addr;
  description?: string | null;
  end_time: Timestamp;
  event_services: EventService[];
  extension?: Empty | null;
  id: number;
  managing_groups: string[];
  start_time: Timestamp;
  status: EventStatus;
  timezone?: string | null;
  title: string;
}
export interface EventService {
  description?: string | null;
  msgs: CosmosMsgForEmpty[];
  name: string;
  target_contract?: string | null;
}
export interface EventGaugeResponse {
  begin_msgs: CosmosMsgForEmpty[];
  end_msgs: CosmosMsgForEmpty[];
  event_id: number;
  group_gauges: GroupGaugeSummary[];
}
export interface GroupGaugeSummary {
  gauges: GaugeConfig[];
  group_id: string;
}
export interface GaugeConfig {
  begin_msgs: CosmosMsgForEmpty[];
  end_msgs: CosmosMsgForEmpty[];
  label: string;
}
export interface HooksResponse {
  hooks: string[];
}
export interface GroupResponse {
  group: Group;
}
export interface GroupsManagingEventResponse {
  groups: Group[];
}
export interface InfoResponse {
  info: ContractVersion;
}
export interface EventListResponseForEmpty {
  events: EventResponseForEmpty[];
}
export interface AgendaResponse {
  events: EventResponseForEmpty[];
  count: number;
}
export interface GroupListResponse {
  groups: Group[];
}