/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { EventSupplierType, InstantiateMsg, GroupInit, EventSupplierInit, ExecuteMsg, Timestamp, Uint64, CosmosMsgForEmpty, BankMsg, Uint128, StakingMsg, DistributionMsg, Binary, IbcMsg, WasmMsg, GovMsg, VoteOption, Decimal, Empty, EventServiceInit, Coin, AnyMsg, IbcTimeout, IbcTimeoutBlock, IbcAcknowledgement, IbcFee, WeightedVoteOption, QueryMsg, EventFilter, EventStatus, MigrateMsg, Addr, DumpStateResponse, ContractVersion, Group, EventSupplier, EventResponseForEmpty, EventForEmpty, EventService, EventGaugeResponse, GroupGaugeSummary, GaugeConfig, HooksResponse, GroupResponse, GroupsManagingEventResponse, InfoResponse, EventListResponseForEmpty, GroupListResponse, AgendaResponse } from "./DaoCalendar.types";
export interface DaoCalendarReadOnlyInterface {
  contractAddress: string;
  event: ({
    eventId
  }: {
    eventId: number;
  }) => Promise<EventResponseForEmpty>;
  listEvents: ({
    filter,
    limit,
    startAfter
  }: {
    filter?: EventFilter;
    limit?: number;
    startAfter?: number;
  }) => Promise<EventListResponseForEmpty>;
  reverseEvents: ({
    filter,
    limit,
    startBefore
  }: {
    filter?: EventFilter;
    limit?: number;
    startBefore?: number;
  }) => Promise<EventListResponseForEmpty>;
  listGroups: () => Promise<GroupListResponse>;
  group: ({
    groupId
  }: {
    groupId: string;
  }) => Promise<GroupResponse>;
  groupsManagingEvent: ({
    eventId
  }: {
    eventId: number;
  }) => Promise<GroupsManagingEventResponse>;
  eventGauges: ({
    eventId
  }: {
    eventId: number;
  }) => Promise<EventGaugeResponse>;
  eventCount: () => Promise<Uint64>;
  eventHooks: () => Promise<HooksResponse>;
  dumpState: () => Promise<DumpStateResponse>;
  dao: () => Promise<Addr>;
  info: () => Promise<InfoResponse>;
  nextProposalId: () => Promise<Uint64>;
  agenda: ({
    from,
    limit
  }: {
    from?: Timestamp;
    limit?: number;
  }) => Promise<AgendaResponse>;
}
export class DaoCalendarQueryClient implements DaoCalendarReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.event = this.event.bind(this);
    this.listEvents = this.listEvents.bind(this);
    this.reverseEvents = this.reverseEvents.bind(this);
    this.listGroups = this.listGroups.bind(this);
    this.group = this.group.bind(this);
    this.groupsManagingEvent = this.groupsManagingEvent.bind(this);
    this.eventGauges = this.eventGauges.bind(this);
    this.eventCount = this.eventCount.bind(this);
    this.eventHooks = this.eventHooks.bind(this);
    this.dumpState = this.dumpState.bind(this);
    this.dao = this.dao.bind(this);
    this.info = this.info.bind(this);
    this.nextProposalId = this.nextProposalId.bind(this);
    this.agenda = this.agenda.bind(this);
  }
  event = async ({
    eventId
  }: {
    eventId: number;
  }): Promise<EventResponseForEmpty> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event: {
        event_id: eventId
      }
    });
  };
  listEvents = async ({
    filter,
    limit,
    startAfter
  }: {
    filter?: EventFilter;
    limit?: number;
    startAfter?: number;
  }): Promise<EventListResponseForEmpty> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_events: {
        filter,
        limit,
        start_after: startAfter
      }
    });
  };
  reverseEvents = async ({
    filter,
    limit,
    startBefore
  }: {
    filter?: EventFilter;
    limit?: number;
    startBefore?: number;
  }): Promise<EventListResponseForEmpty> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reverse_events: {
        filter,
        limit,
        start_before: startBefore
      }
    });
  };
  listGroups = async (): Promise<GroupListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      list_groups: {}
    });
  };
  group = async ({
    groupId
  }: {
    groupId: string;
  }): Promise<GroupResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      group: {
        group_id: groupId
      }
    });
  };
  groupsManagingEvent = async ({
    eventId
  }: {
    eventId: number;
  }): Promise<GroupsManagingEventResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      groups_managing_event: {
        event_id: eventId
      }
    });
  };
  eventGauges = async ({
    eventId
  }: {
    eventId: number;
  }): Promise<EventGaugeResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event_gauges: {
        event_id: eventId
      }
    });
  };
  eventCount = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event_count: {}
    });
  };
  eventHooks = async (): Promise<HooksResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      event_hooks: {}
    });
  };
  dumpState = async (): Promise<DumpStateResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      dump_state: {}
    });
  };
  dao = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      dao: {}
    });
  };
  info = async (): Promise<InfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      info: {}
    });
  };
  nextProposalId = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      next_proposal_id: {}
    });
  };
  agenda = async ({
    from,
    limit
  }: {
    from?: Timestamp;
    limit?: number;
  }): Promise<AgendaResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      agenda: {
        from,
        limit
      }
    });
  };
}
export interface DaoCalendarInterface extends DaoCalendarReadOnlyInterface {
  contractAddress: string;
  sender: string;
  createEvent: ({
    description,
    endTime,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime: Timestamp;
    extension?: Empty;
    managingGroups: string[];
    services?: EventServiceInit[];
    startTime: Timestamp;
    title: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateEvent: ({
    description,
    endTime,
    eventId,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime?: Timestamp;
    eventId: number;
    extension?: Empty;
    managingGroups?: string[];
    services?: EventServiceInit[];
    startTime?: Timestamp;
    title?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  cancelEvent: ({
    eventId
  }: {
    eventId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerEventGauges: ({
    beginMsgs,
    endMsgs,
    eventId
  }: {
    beginMsgs: CosmosMsgForEmpty[];
    endMsgs: CosmosMsgForEmpty[];
    eventId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  triggerEventStart: ({
    eventId
  }: {
    eventId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  triggerEventEnd: ({
    eventId
  }: {
    eventId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerGroup: ({
    group
  }: {
    group: GroupInit;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateGroup: ({
    groupId,
    suppliers
  }: {
    groupId: string;
    suppliers?: EventSupplierInit[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  removeGroup: ({
    groupId
  }: {
    groupId: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  renewCalendar: ({
    limit
  }: {
    limit?: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  addEventHook: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  removeEventHook: ({
    address
  }: {
    address: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class DaoCalendarClient extends DaoCalendarQueryClient implements DaoCalendarInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createEvent = this.createEvent.bind(this);
    this.updateEvent = this.updateEvent.bind(this);
    this.cancelEvent = this.cancelEvent.bind(this);
    this.registerEventGauges = this.registerEventGauges.bind(this);
    this.triggerEventStart = this.triggerEventStart.bind(this);
    this.triggerEventEnd = this.triggerEventEnd.bind(this);
    this.registerGroup = this.registerGroup.bind(this);
    this.updateGroup = this.updateGroup.bind(this);
    this.removeGroup = this.removeGroup.bind(this);
    this.renewCalendar = this.renewCalendar.bind(this);
    this.addEventHook = this.addEventHook.bind(this);
    this.removeEventHook = this.removeEventHook.bind(this);
  }
  createEvent = async ({
    description,
    endTime,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime: Timestamp;
    extension?: Empty;
    managingGroups: string[];
    services?: EventServiceInit[];
    startTime: Timestamp;
    title: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_event: {
        description,
        end_time: endTime,
        extension,
        managing_groups: managingGroups,
        services,
        start_time: startTime,
        title
      }
    }, fee_, memo_, funds_);
  };
  updateEvent = async ({
    description,
    endTime,
    eventId,
    extension,
    managingGroups,
    services,
    startTime,
    title
  }: {
    description?: string;
    endTime?: Timestamp;
    eventId: number;
    extension?: Empty;
    managingGroups?: string[];
    services?: EventServiceInit[];
    startTime?: Timestamp;
    title?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_event: {
        description,
        end_time: endTime,
        event_id: eventId,
        extension,
        managing_groups: managingGroups,
        services,
        start_time: startTime,
        title
      }
    }, fee_, memo_, funds_);
  };
  cancelEvent = async ({
    eventId
  }: {
    eventId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      cancel_event: {
        event_id: eventId
      }
    }, fee_, memo_, funds_);
  };
  registerEventGauges = async ({
    beginMsgs,
    endMsgs,
    eventId
  }: {
    beginMsgs: CosmosMsgForEmpty[];
    endMsgs: CosmosMsgForEmpty[];
    eventId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_event_gauges: {
        begin_msgs: beginMsgs,
        end_msgs: endMsgs,
        event_id: eventId
      }
    }, fee_, memo_, funds_);
  };
  triggerEventStart = async ({
    eventId
  }: {
    eventId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      trigger_event_start: {
        event_id: eventId
      }
    }, fee_, memo_, funds_);
  };
  triggerEventEnd = async ({
    eventId
  }: {
    eventId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      trigger_event_end: {
        event_id: eventId
      }
    }, fee_, memo_, funds_);
  };
  registerGroup = async ({
    group
  }: {
    group: GroupInit;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_group: {
        group
      }
    }, fee_, memo_, funds_);
  };
  updateGroup = async ({
    groupId,
    suppliers
  }: {
    groupId: string;
    suppliers?: EventSupplierInit[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_group: {
        group_id: groupId,
        suppliers
      }
    }, fee_, memo_, funds_);
  };
  removeGroup = async ({
    groupId
  }: {
    groupId: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_group: {
        group_id: groupId
      }
    }, fee_, memo_, funds_);
  };
  renewCalendar = async ({
    limit
  }: {
    limit?: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      renew_calendar: {
        limit
      }
    }, fee_, memo_, funds_);
  };
  addEventHook = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_event_hook: {
        address
      }
    }, fee_, memo_, funds_);
  };
  removeEventHook = async ({
    address
  }: {
    address: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_event_hook: {
        address
      }
    }, fee_, memo_, funds_);
  };
}