/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Timestamp, Uint64, Uint128, InstantiateMsg, Coin, ExecuteMsg, QueryMsg, CosmosMsgForEmpty, BankMsg, Binary, IbcMsg, WasmMsg, GovMsg, VoteOption, Decimal, Empty, IbcTimeout, IbcTimeoutBlock, WeightedVoteOption, AdminListResponse, CanExecuteResponse, ConfigResponse, HasEndedResponse, HasMemberResponse, HasStartedResponse, IsActiveResponse, MerkleRootResponse, MerkleTreeURIResponse } from "./WhitelistMerkletree.types";
import { WhitelistMerkletreeQueryClient } from "./WhitelistMerkletree.client";
export const whitelistMerkletreeQueryKeys = {
  contract: ([{
    contract: "whitelistMerkletree"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...whitelistMerkletreeQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  hasStarted: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "has_started",
    args
  }] as const),
  hasEnded: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "has_ended",
    args
  }] as const),
  isActive: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "is_active",
    args
  }] as const),
  hasMember: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "has_member",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  adminList: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "admin_list",
    args
  }] as const),
  canExecute: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "can_execute",
    args
  }] as const),
  merkleRoot: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "merkle_root",
    args
  }] as const),
  merkleTreeURI: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...whitelistMerkletreeQueryKeys.address(contractAddress)[0],
    method: "merkle_tree_u_r_i",
    args
  }] as const)
};
export const whitelistMerkletreeQueries = {
  hasStarted: <TData = HasStartedResponse,>({
    client,
    options
  }: WhitelistMerkletreeHasStartedQuery<TData>): UseQueryOptions<HasStartedResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.hasStarted(client?.contractAddress),
    queryFn: () => client ? client.hasStarted() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  hasEnded: <TData = HasEndedResponse,>({
    client,
    options
  }: WhitelistMerkletreeHasEndedQuery<TData>): UseQueryOptions<HasEndedResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.hasEnded(client?.contractAddress),
    queryFn: () => client ? client.hasEnded() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  isActive: <TData = IsActiveResponse,>({
    client,
    options
  }: WhitelistMerkletreeIsActiveQuery<TData>): UseQueryOptions<IsActiveResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.isActive(client?.contractAddress),
    queryFn: () => client ? client.isActive() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  hasMember: <TData = HasMemberResponse,>({
    client,
    args,
    options
  }: WhitelistMerkletreeHasMemberQuery<TData>): UseQueryOptions<HasMemberResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.hasMember(client?.contractAddress, args),
    queryFn: () => client ? client.hasMember({
      member: args.member,
      proofHashes: args.proofHashes
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: WhitelistMerkletreeConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  adminList: <TData = AdminListResponse,>({
    client,
    options
  }: WhitelistMerkletreeAdminListQuery<TData>): UseQueryOptions<AdminListResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.adminList(client?.contractAddress),
    queryFn: () => client ? client.adminList() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  canExecute: <TData = CanExecuteResponse,>({
    client,
    args,
    options
  }: WhitelistMerkletreeCanExecuteQuery<TData>): UseQueryOptions<CanExecuteResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.canExecute(client?.contractAddress, args),
    queryFn: () => client ? client.canExecute({
      msg: args.msg,
      sender: args.sender
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  merkleRoot: <TData = MerkleRootResponse,>({
    client,
    options
  }: WhitelistMerkletreeMerkleRootQuery<TData>): UseQueryOptions<MerkleRootResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.merkleRoot(client?.contractAddress),
    queryFn: () => client ? client.merkleRoot() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  merkleTreeURI: <TData = MerkleTreeURIResponse,>({
    client,
    options
  }: WhitelistMerkletreeMerkleTreeURIQuery<TData>): UseQueryOptions<MerkleTreeURIResponse, Error, TData> => ({
    queryKey: whitelistMerkletreeQueryKeys.merkleTreeURI(client?.contractAddress),
    queryFn: () => client ? client.merkleTreeURI() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface WhitelistMerkletreeReactQuery<TResponse, TData = TResponse> {
  client: WhitelistMerkletreeQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface WhitelistMerkletreeMerkleTreeURIQuery<TData> extends WhitelistMerkletreeReactQuery<MerkleTreeURIResponse, TData> {}
export function useWhitelistMerkletreeMerkleTreeURIQuery<TData = MerkleTreeURIResponse>({
  client,
  options
}: WhitelistMerkletreeMerkleTreeURIQuery<TData>) {
  return useQuery<MerkleTreeURIResponse, Error, TData>(whitelistMerkletreeQueryKeys.merkleTreeURI(client?.contractAddress), () => client ? client.merkleTreeURI() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeMerkleRootQuery<TData> extends WhitelistMerkletreeReactQuery<MerkleRootResponse, TData> {}
export function useWhitelistMerkletreeMerkleRootQuery<TData = MerkleRootResponse>({
  client,
  options
}: WhitelistMerkletreeMerkleRootQuery<TData>) {
  return useQuery<MerkleRootResponse, Error, TData>(whitelistMerkletreeQueryKeys.merkleRoot(client?.contractAddress), () => client ? client.merkleRoot() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeCanExecuteQuery<TData> extends WhitelistMerkletreeReactQuery<CanExecuteResponse, TData> {
  args: {
    msg: CosmosMsgForEmpty;
    sender: string;
  };
}
export function useWhitelistMerkletreeCanExecuteQuery<TData = CanExecuteResponse>({
  client,
  args,
  options
}: WhitelistMerkletreeCanExecuteQuery<TData>) {
  return useQuery<CanExecuteResponse, Error, TData>(whitelistMerkletreeQueryKeys.canExecute(client?.contractAddress, args), () => client ? client.canExecute({
    msg: args.msg,
    sender: args.sender
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeAdminListQuery<TData> extends WhitelistMerkletreeReactQuery<AdminListResponse, TData> {}
export function useWhitelistMerkletreeAdminListQuery<TData = AdminListResponse>({
  client,
  options
}: WhitelistMerkletreeAdminListQuery<TData>) {
  return useQuery<AdminListResponse, Error, TData>(whitelistMerkletreeQueryKeys.adminList(client?.contractAddress), () => client ? client.adminList() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeConfigQuery<TData> extends WhitelistMerkletreeReactQuery<ConfigResponse, TData> {}
export function useWhitelistMerkletreeConfigQuery<TData = ConfigResponse>({
  client,
  options
}: WhitelistMerkletreeConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(whitelistMerkletreeQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeHasMemberQuery<TData> extends WhitelistMerkletreeReactQuery<HasMemberResponse, TData> {
  args: {
    member: string;
    proofHashes: string[];
  };
}
export function useWhitelistMerkletreeHasMemberQuery<TData = HasMemberResponse>({
  client,
  args,
  options
}: WhitelistMerkletreeHasMemberQuery<TData>) {
  return useQuery<HasMemberResponse, Error, TData>(whitelistMerkletreeQueryKeys.hasMember(client?.contractAddress, args), () => client ? client.hasMember({
    member: args.member,
    proofHashes: args.proofHashes
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeIsActiveQuery<TData> extends WhitelistMerkletreeReactQuery<IsActiveResponse, TData> {}
export function useWhitelistMerkletreeIsActiveQuery<TData = IsActiveResponse>({
  client,
  options
}: WhitelistMerkletreeIsActiveQuery<TData>) {
  return useQuery<IsActiveResponse, Error, TData>(whitelistMerkletreeQueryKeys.isActive(client?.contractAddress), () => client ? client.isActive() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeHasEndedQuery<TData> extends WhitelistMerkletreeReactQuery<HasEndedResponse, TData> {}
export function useWhitelistMerkletreeHasEndedQuery<TData = HasEndedResponse>({
  client,
  options
}: WhitelistMerkletreeHasEndedQuery<TData>) {
  return useQuery<HasEndedResponse, Error, TData>(whitelistMerkletreeQueryKeys.hasEnded(client?.contractAddress), () => client ? client.hasEnded() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface WhitelistMerkletreeHasStartedQuery<TData> extends WhitelistMerkletreeReactQuery<HasStartedResponse, TData> {}
export function useWhitelistMerkletreeHasStartedQuery<TData = HasStartedResponse>({
  client,
  options
}: WhitelistMerkletreeHasStartedQuery<TData>) {
  return useQuery<HasStartedResponse, Error, TData>(whitelistMerkletreeQueryKeys.hasStarted(client?.contractAddress), () => client ? client.hasStarted() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}