/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { selectorFamily } from "recoil";
import { cosmWasmClient } from "./chain";
import { Timestamp, Uint64, Uint128, InstantiateMsg, Coin, ExecuteMsg, QueryMsg, CosmosMsgForEmpty, BankMsg, Binary, IbcMsg, WasmMsg, GovMsg, VoteOption, Decimal, Empty, IbcTimeout, IbcTimeoutBlock, WeightedVoteOption, AdminListResponse, CanExecuteResponse, ConfigResponse, HasEndedResponse, HasMemberResponse, HasStartedResponse, IsActiveResponse, MerkleRootResponse, MerkleTreeURIResponse } from "./WhitelistMerkletree.types";
import { WhitelistMerkletreeQueryClient } from "./WhitelistMerkletree.client";
type QueryClientParams = {
  contractAddress: string;
};
export const queryClient = selectorFamily<WhitelistMerkletreeQueryClient, QueryClientParams>({
  key: "whitelistMerkletreeQueryClient",
  get: ({
    contractAddress
  }) => ({
    get
  }) => {
    const client = get(cosmWasmClient);
    return new WhitelistMerkletreeQueryClient(client, contractAddress);
  }
});
export const hasStartedSelector = selectorFamily<HasStartedResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["hasStarted"]>;
}>({
  key: "whitelistMerkletreeHasStarted",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.hasStarted(...params);
  }
});
export const hasEndedSelector = selectorFamily<HasEndedResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["hasEnded"]>;
}>({
  key: "whitelistMerkletreeHasEnded",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.hasEnded(...params);
  }
});
export const isActiveSelector = selectorFamily<IsActiveResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["isActive"]>;
}>({
  key: "whitelistMerkletreeIsActive",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.isActive(...params);
  }
});
export const hasMemberSelector = selectorFamily<HasMemberResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["hasMember"]>;
}>({
  key: "whitelistMerkletreeHasMember",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.hasMember(...params);
  }
});
export const configSelector = selectorFamily<ConfigResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["config"]>;
}>({
  key: "whitelistMerkletreeConfig",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.config(...params);
  }
});
export const adminListSelector = selectorFamily<AdminListResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["adminList"]>;
}>({
  key: "whitelistMerkletreeAdminList",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.adminList(...params);
  }
});
export const canExecuteSelector = selectorFamily<CanExecuteResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["canExecute"]>;
}>({
  key: "whitelistMerkletreeCanExecute",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.canExecute(...params);
  }
});
export const merkleRootSelector = selectorFamily<MerkleRootResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["merkleRoot"]>;
}>({
  key: "whitelistMerkletreeMerkleRoot",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.merkleRoot(...params);
  }
});
export const merkleTreeURISelector = selectorFamily<MerkleTreeURIResponse, QueryClientParams & {
  params: Parameters<WhitelistMerkletreeQueryClient["merkleTreeURI"]>;
}>({
  key: "whitelistMerkletreeMerkleTreeURI",
  get: ({
    params,
    ...queryClientParams
  }) => async ({
    get
  }) => {
    const client = get(queryClient(queryClientParams));
    return await client.merkleTreeURI(...params);
  }
});