// Auto-generated by gen-tools.
// Do not edit manually.

/** The message types of the bank module.

See https://github.com/cosmos/cosmos-sdk/blob/v0.40.0/proto/cosmos/bank/v1beta1/tx.proto */
export type BankMsg =
  | { send: { amount: Coin[]; to_address: string } } |
  | { burn: { amount: Coin[] } };

/** Binary is a wrapper around Vec<u8> to add base64 de/serialization with serde. It also adds some helper methods to help encode inline.

This is only needed as serde-json-{core,wasm} has a horrible encoding for Vec<u8>. See also <https://github.com/CosmWasm/cosmwasm/blob/main/docs/MESSAGE_TYPES.md>. */
export type Binary = string;

export interface Coin {
  amount: Uint256;
  denom: string;
}

export type CosmosMsgForEmpty =
  | { bank: BankMsg } |
  | { custom: Empty } |
  | { wasm: WasmMsg };

/** An empty struct that serves as a placeholder in different places, such as contracts that don't set a custom message.

It is designed to be expressible in correct JSON and JSON Schema but contains no meaningful data. Previously we used enums without cases, but those cannot represented as valid JSON Schema (https://github.com/CosmWasm/cosmwasm/issues/451) */
export interface Empty {
}

/** An implementation of u256 that is using strings for JSON encoding/decoding, such that the full u256 range can be used for clients that convert JSON numbers to floats, like JavaScript and jq.

# Examples

Use `new` to create instances out of u128, `from` for other primitive uint types or `from_be_bytes` to provide big endian bytes:

``` # use cosmwasm_std::Uint256; let a = Uint256::new(258u128); let b = Uint256::from(258u16); let c = Uint256::from_be_bytes([ 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 1u8, 2u8, ]); assert_eq!(a, b); assert_eq!(a, c); ``` */
export type Uint256 = string;

/** The message types of the wasm module.

See https://github.com/CosmWasm/wasmd/blob/v0.14.0/x/wasm/internal/types/tx.proto */
export type WasmMsg =
  | { execute: { contract_addr: string; funds: Coin[]; msg: Binary } } |
  | { instantiate: { admin: unknown; code_id: number; funds: Coin[]; label: string; msg: Binary } } |
  | { migrate: { contract_addr: string; msg: Binary; new_code_id: number } } |
  | { update_admin: { admin: string; contract_addr: string } } |
  | { clear_admin: { contract_addr: string } };

export interface InstantiateMsg {
  admins: string[];
  admins_mutable: boolean;
  merkle_root: string;
  merkle_tree_uri?: unknown;
}

export type ExecuteMsg =
  | { update_admins: { admins: string[] } } |
  | { freeze: Record<string, unknown> };

export type QueryMsg =
  | { has_member: { member: string; proof_hashes: string[] } } |
  | { admin_list: Record<string, unknown> } |
  | { can_execute: { msg: CosmosMsgForEmpty; sender: string } } |
  | { merkle_root: Record<string, unknown> } |
  | { merkle_tree_u_r_i: Record<string, unknown> };

export interface AdminListResponse {
  admins: string[];
  mutable: boolean;
}

export interface CanExecuteResponse {
  can_execute: boolean;
}

export interface HasMemberResponse {
  has_member: boolean;
}

export interface MerkleRootResponse {
  merkle_root: string;
}

export interface MerkleTreeURIResponse {
  merkle_tree_uri?: unknown;
}

