/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface InstantiateMsg {
  admins: string[];
  admins_mutable: boolean;
  end_time: Timestamp;
  merkle_root: string;
  merkle_tree_uri?: string | null;
  mint_price: Coin;
  per_address_limit: number;
  start_time: Timestamp;
}
export interface Coin {
  amount: Uint128;
  denom: string;
}
export type ExecuteMsg = {
  update_start_time: Timestamp;
} | {
  update_end_time: Timestamp;
} | {
  update_admins: {
    admins: string[];
  };
} | {
  freeze: {};
};
export type QueryMsg = {
  has_started: {};
} | {
  has_ended: {};
} | {
  is_active: {};
} | {
  has_member: {
    member: string;
    proof_hashes: string[];
  };
} | {
  config: {};
} | {
  admin_list: {};
} | {
  can_execute: {
    msg: CosmosMsgForEmpty;
    sender: string;
  };
} | {
  merkle_root: {};
} | {
  merkle_tree_u_r_i: {};
};
export type CosmosMsgForEmpty = {
  bank: BankMsg;
} | {
  custom: Empty;
} | {
  staking: StakingMsg;
} | {
  distribution: DistributionMsg;
} | {
  stargate: {
    type_url: string;
    value: Binary;
  };
} | {
  ibc: IbcMsg;
} | {
  wasm: WasmMsg;
} | {
  gov: GovMsg;
};
export type BankMsg = {
  send: {
    amount: Coin[];
    to_address: string;
  };
} | {
  burn: {
    amount: Coin[];
  };
};
export type StakingMsg = {
  delegate: {
    amount: Coin;
    validator: string;
  };
} | {
  undelegate: {
    amount: Coin;
    validator: string;
  };
} | {
  redelegate: {
    amount: Coin;
    dst_validator: string;
    src_validator: string;
  };
};
export type DistributionMsg = {
  set_withdraw_address: {
    address: string;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
  };
};
export type Binary = string;
export type IbcMsg = {
  transfer: {
    amount: Coin;
    channel_id: string;
    memo?: string | null;
    timeout: IbcTimeout;
    to_address: string;
  };
} | {
  send_packet: {
    channel_id: string;
    data: Binary;
    timeout: IbcTimeout;
  };
} | {
  close_channel: {
    channel_id: string;
  };
};
export type WasmMsg = {
  execute: {
    contract_addr: string;
    funds: Coin[];
    msg: Binary;
  };
} | {
  instantiate: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
  };
} | {
  instantiate2: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    salt: Binary;
  };
} | {
  migrate: {
    contract_addr: string;
    msg: Binary;
    new_code_id: number;
  };
} | {
  update_admin: {
    admin: string;
    contract_addr: string;
  };
} | {
  clear_admin: {
    contract_addr: string;
  };
};
export type GovMsg = {
  vote: {
    option: VoteOption;
    proposal_id: number;
  };
} | {
  vote_weighted: {
    options: WeightedVoteOption[];
    proposal_id: number;
  };
};
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
export type Decimal = string;
export interface Empty {}
export interface IbcTimeout {
  block?: IbcTimeoutBlock | null;
  timestamp?: Timestamp | null;
}
export interface IbcTimeoutBlock {
  height: number;
  revision: number;
}
export interface WeightedVoteOption {
  option: VoteOption;
  weight: Decimal;
}
export interface AdminListResponse {
  admins: string[];
  mutable: boolean;
}
export interface CanExecuteResponse {
  can_execute: boolean;
}
export interface ConfigResponse {
  end_time: Timestamp;
  is_active: boolean;
  member_limit: number;
  mint_price: Coin;
  num_members: number;
  per_address_limit: number;
  start_time: Timestamp;
}
export interface HasEndedResponse {
  has_ended: boolean;
}
export interface HasMemberResponse {
  has_member: boolean;
}
export interface HasStartedResponse {
  has_started: boolean;
}
export interface IsActiveResponse {
  is_active: boolean;
}
export interface MerkleRootResponse {
  merkle_root: string;
}
export interface MerkleTreeURIResponse {
  merkle_tree_uri?: string | null;
}