// Auto-generated by gen-tools.
import type { WhitelistMtree } from './WhitelistMtree.types';
import type { Coin } from '@cosmjs/amino';
import type { MsgExecuteContract } from 'cosmjs-types/cosmwasm/wasm/v1/tx';

export class WhitelistMtreeMsgComposer {
  readonly contractAddress: string;

  constructor(contractAddress: string) {
    this.contractAddress = contractAddress;
  }

  updateAdmins(msg: Extract<WhitelistMtreeType, { update_admins: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

  freeze(msg: Extract<WhitelistMtreeType, { freeze: unknown }>): MsgExecuteContract {
    return {
      typeUrl: '/cosmwasm.wasm.v1.MsgExecuteContract',
      value: {
        sender: '',
        contract: this.contractAddress,
        msg: Buffer.from(JSON.stringify(msg)),
        funds: [] as Coin[],
      },
    } as MsgExecuteContract;
  }

}
