/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { Timestamp, Uint64, Uint128, InstantiateMsg, Coin, ExecuteMsg, QueryMsg, CosmosMsgForEmpty, BankMsg, StakingMsg, DistributionMsg, Binary, IbcMsg, WasmMsg, GovMsg, VoteOption, Decimal, Empty, IbcTimeout, IbcTimeoutBlock, WeightedVoteOption, AdminListResponse, CanExecuteResponse, ConfigResponse, HasEndedResponse, HasMemberResponse, HasStartedResponse, IsActiveResponse, MerkleRootResponse, MerkleTreeURIResponse } from "./WhitelistMtree.types";
export interface WhitelistMtreeReadOnlyInterface {
  contractAddress: string;
  hasStarted: () => Promise<HasStartedResponse>;
  hasEnded: () => Promise<HasEndedResponse>;
  isActive: () => Promise<IsActiveResponse>;
  hasMember: ({
    member,
    proofHashes
  }: {
    member: string;
    proofHashes: string[];
  }) => Promise<HasMemberResponse>;
  config: () => Promise<ConfigResponse>;
  adminList: () => Promise<AdminListResponse>;
  canExecute: ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }) => Promise<CanExecuteResponse>;
  merkleRoot: () => Promise<MerkleRootResponse>;
  merkleTreeURI: () => Promise<MerkleTreeURIResponse>;
}
export class WhitelistMtreeQueryClient implements WhitelistMtreeReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.hasStarted = this.hasStarted.bind(this);
    this.hasEnded = this.hasEnded.bind(this);
    this.isActive = this.isActive.bind(this);
    this.hasMember = this.hasMember.bind(this);
    this.config = this.config.bind(this);
    this.adminList = this.adminList.bind(this);
    this.canExecute = this.canExecute.bind(this);
    this.merkleRoot = this.merkleRoot.bind(this);
    this.merkleTreeURI = this.merkleTreeURI.bind(this);
  }
  hasStarted = async (): Promise<HasStartedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      has_started: {}
    });
  };
  hasEnded = async (): Promise<HasEndedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      has_ended: {}
    });
  };
  isActive = async (): Promise<IsActiveResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_active: {}
    });
  };
  hasMember = async ({
    member,
    proofHashes
  }: {
    member: string;
    proofHashes: string[];
  }): Promise<HasMemberResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      has_member: {
        member,
        proof_hashes: proofHashes
      }
    });
  };
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  adminList = async (): Promise<AdminListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin_list: {}
    });
  };
  canExecute = async ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }): Promise<CanExecuteResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      can_execute: {
        msg,
        sender
      }
    });
  };
  merkleRoot = async (): Promise<MerkleRootResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      merkle_root: {}
    });
  };
  merkleTreeURI = async (): Promise<MerkleTreeURIResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      merkle_tree_u_r_i: {}
    });
  };
}
export interface WhitelistMtreeInterface extends WhitelistMtreeReadOnlyInterface {
  contractAddress: string;
  sender: string;
  updateStartTime: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateEndTime: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateAdmins: ({
    admins
  }: {
    admins: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  freeze: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class WhitelistMtreeClient extends WhitelistMtreeQueryClient implements WhitelistMtreeInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateStartTime = this.updateStartTime.bind(this);
    this.updateEndTime = this.updateEndTime.bind(this);
    this.updateAdmins = this.updateAdmins.bind(this);
    this.freeze = this.freeze.bind(this);
  }
  updateStartTime = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_start_time: {}
    }, fee_, memo_, funds_);
  };
  updateEndTime = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_end_time: {}
    }, fee_, memo_, funds_);
  };
  updateAdmins = async ({
    admins
  }: {
    admins: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_admins: {
        admins
      }
    }, fee_, memo_, funds_);
  };
  freeze = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      freeze: {}
    }, fee_, memo_, funds_);
  };
}