// Auto-generated by gen-tools.
import type { WhitelistMtree as WhitelistMtreeType } from './WhitelistMtree.types';
import type { CosmWasmClient, SigningCosmWasmClient } from '@cosmjs/cosmwasm-stargate';

export interface WhitelistMtreeQueryClient {
  readonly client: CosmWasmClient;
  readonly contractAddress: string;

  hasMember(params: Extract<WhitelistMtreeType, { has_member: unknown }>['has_member']): Promise<unknown>;
  adminList(params: Extract<WhitelistMtreeType, { admin_list: unknown }>['admin_list']): Promise<unknown>;
  canExecute(params: Extract<WhitelistMtreeType, { can_execute: unknown }>['can_execute']): Promise<unknown>;
  merkleRoot(params: Extract<WhitelistMtreeType, { merkle_root: unknown }>['merkle_root']): Promise<unknown>;
  merkleTreeURI(params: Extract<WhitelistMtreeType, { merkle_tree_u_r_i: unknown }>['merkle_tree_u_r_i']): Promise<unknown>;
}

export interface WhitelistMtreeExecuteClient {
  readonly client: SigningCosmWasmClient;
  readonly contractAddress: string;
  readonly sender: string;

  updateAdmins(params: Extract<WhitelistMtreeType, { update_admins: unknown }>['update_admins']): Promise<string>;
  freeze(params: Extract<WhitelistMtreeType, { freeze: unknown }>['freeze']): Promise<string>;
}
