[package]
name = "cw-infuser"
version  = { workspace = true }
authors = ["hard-nett <hardnettt@proton.me>"]
edition = "2024"
exclude = ["scripts"]
[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
# cw-orchestrator interface
interface = ["cw-orch"]
# zk-cosmwasmvm api support
zk = ["cosmwasm-std/zk"]

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std = { workspace = true }
cw-controllers = { workspace = true }
cw-infusions = { workspace = true }
cw-orch = { workspace = true, optional = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw721 = { workspace = true }
nois = { version = "2.0.0" }
rand_xoshiro = { version = "0.6.0", default-features = false }
semver = "1"
sha2 = { version = "0.10.8", default-features = false }
shuffle = { git = "https://github.com/webmaster128/shuffle", branch = "rm-getrandom", version = "0.1.7" }
thiserror = { version = "1.0.58" }
url = "2.2.2"

[dev-dependencies]
cw-multi-test = { package = "abstract-cw-multi-test", path = "../../../cw-multi-test-fork" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
