[package]
name = "cw-infusions"
authors = ["hard-nett <hardnettt@proton.me>"]
description = "Rust definition of name service metadata, used by Bitsong Accounts."
version = "0.1.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22.1"
sha2 = { version = "0.10.8", default-features = false }
cosmwasm-schema =  { workspace = true}
cosmwasm-std = { workspace = true, features = [ ] }
