[package]
name = "cw-infusions"
authors = ["hard-nett <hardnettt@proton.me>"]
description = "Rust definition of name service metadata, used by Bitsong Accounts."
version = "0.1.0"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sg721 = "^3.3"
base64 = "0.22.1"
cosmwasm-std = { workspace = true, features = [
  "cosmwasm_1_4",
  # Enable this if you only deploy to chains that have CosmWasm 2.0 or higher
  # "cosmwasm_2_0",
] }
cosmwasm-schema =  { workspace = true}
cw-orch = "0.25.0"
sha2 = { version = "0.10.8", default-features = false }
