[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[dependencies]
cw-orch = { workspace = true, features = ["daemon"] }
cosmwasm-std = { workspace = true }
cw-utils = { workspace = true }
itertools = { workspace = true }