[package]
name = "cw-svg-minter"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# use library feature to disable all instantiate/execute/query exports
library = []
interface = ["cw-orch"]

[dependencies]
cw-orch =  { workspace = true, optional = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw2 = { workspace = true }
cw-ownable = "2.1.0"
cw-storage-plus = { workspace = true }
cw721-svg = { path = "../cw721-svg", features = ["library"] }
schemars = "0.8.16"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
sha2 = { workspace = true }
thiserror = { version = "1.0.58" }
